### ISSUE TITLE
opPlayerNocheat didn't banned `/fill`

### ISSUE THREAD

**Issue by Mehver** [TISUnion/Carpet-TIS-Addition#101]
## Motivation

opPlayerNocheat didn't banned `/fill`

虽然这个也给fabric-carpet提交了，但是他们修的不一定很快。想问问这边是否乐意解决一下。

## Description

即使开了opPlayerNocheat，op还是能使用fill获取重要物资。我们服有人直接fill了一堆远古残骸出来，挺破坏平衡的

**Comment by Fallen-Breath** [comment]
意料中的行为。与 #36 #78 重复
