### ISSUE TITLE
Incompatible with Carpet-Fixes (1.20)

### ISSUE THREAD

**Issue by Notoriousi** [TISUnion/Carpet-TIS-Addition#106]
### Bug description

Game doesn't launch when the 2 mods are combined:

-carpet-fixes 1.20-1.15.2
- carpet-tis-addition 1.48.0

### Steps to reproduce

Start minecraft with the 2 mods in it (and also carpet mod)

### Relevant logs

https://mclo.gs/wQhOcdO

### Minecraft version

1.20

### Carpet TIS Addition version

1.48

### Fabric Carpet version

1.4.112

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
yeah, the necessary `@Redirect` mixin for update suppression fix loves to break mod compatibility

**Comment by Fallen-Breath** [comment]
Try https://github.com/TISUnion/Carpet-TIS-Addition/actions/runs/5375809520, the introduced MixinExtras component should handle the update suppression stuffs correctly

**Comment by Notoriousi** [comment]
This build indeed fixes the incompatibility and works as intended (as far as i've tested)

Closing this issue, much thanks!
