### ISSUE TITLE
在Minecraft 1.19.3版本上加载崩溃

### ISSUE THREAD

**Issue by ghost** [TISUnion/Carpet-TIS-Addition#108]
### Bug description

[latest.log](https://github.com/TISUnion/Carpet-TIS-Addition/files/11865686/latest.log)

### Steps to reproduce

根本无法打开游戏，加载时崩溃。log内有帕秋莉手册相关字样，但删除该模组后，tis carpet addition仍报错，PCL2启动器反馈为模组注册失败。

### Minecraft version

1.19.3

### Carpet TIS Addition version

1.48.1

### Fabric Carpet version

1.4.96

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by ghost** [comment]
与carpet fix不兼容，已自行修复，打扰了。

**Comment by Fallen-Breath** [comment]
与 #106 重复
