### ISSUE TITLE
yeetUpdateSuppressionCrash doesn't work with CCE

### ISSUE THREAD

**Issue by Notoriousi** [TISUnion/Carpet-TIS-Addition#109]
### Bug description

Using the new shulker supression method the server still crashes when doing non-player updates to the supressor.

Carpet rules enabled:
yeetUpdateSupressionCrash (default to true)

### Steps to reproduce

1. Have a CCE supressor
2. Update the supressor using a redstone torch and a repeater into the supressor (or any non-player interaction, this is what i use)
3. Crash.

### Expected behavior

As the rule says "Prevent the server from crashing due to StackOverflowError, OutOfMemoryError or ClassCastException"

### Actual behavior

Still crashes

### Relevant logs

https://mclo.gs/ihRo7d6 (with other mods)
https://mclo.gs/4TLjXNY (only using carpetmod and carpetTIS)

### Minecraft version

1.20.1

### Carpet TIS Addition version

1.48.1+build.1458

### Fabric Carpet version

1.4.112+v230608

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
ah I missed the `net.minecraft.world.block.ChainRestrictedNeighborUpdater.SixWayEntry` kind of block update

**Comment by Fallen-Breath** [comment]
Actually not just CCE suppressor, all update suppression exceptions caused by **only** `ChainRestrictedNeighborUpdater.SixWayEntry` are not caught. And CCE is just the easiest way to do that

**Comment by Fallen-Breath** [comment]
Try https://github.com/TISUnion/Carpet-TIS-Addition/actions/runs/5380638597. Notes that it does not contain the compatibility fix for carpet-fixes from the dev branch

**Comment by Notoriousi** [comment]
Works like a charm! But like you said missing the compatibility, is it possible to have them both working or would that require more work?

**Comment by Fallen-Breath** [comment]
You need to wait until the next minor release for that

**Comment by Notoriousi** [comment]
Sweet! Once again, thanks for the mod and the work. Closing this issue now
