### ISSUE TITLE
Minecraft crashes when started

### ISSUE THREAD

**Issue by JNapier18** [TISUnion/Carpet-TIS-Addition#110]
### Bug description

I recently installed Carpet Fixes 1.20-1.15.2 and TIS Addition 1.48.2. However, upon starting Minecraft, it crashes immediately. I attempted to resolve the issue by removing Carpet Fixes, and Minecraft was able to start without any problems. Based on this, I suspect there may be a compatibility issue between these mods. Can you offer any guidance on how to resolve this?

### Steps to reproduce

Start Minecraft

### Minecraft version

1.20.1

### Carpet TIS Addition version

1.48.2

### Fabric Carpet version

1.4.112+v230608

### Other information

Issue only occurs when both Fixes and TIS are installed

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
duplicated with #106
