### ISSUE TITLE
[Feature Request] Reintroduce trapdoor dust redirection

### ISSUE THREAD

**Issue by Rozbiynk** [TISUnion/Carpet-TIS-Addition#111]
### Motivation

1.20 patches dust redirection so there is no way to easily make small suppression (you can still make CCE supressor, but it requires veeeery big supressor)

### Description

Redirect dust when trapdoor with Redstone on top of it opens

**Comment by Fallen-Breath** [comment]
carpet-fixes has the reintroduce since v1.16.0, idk if it meets ur need: https://github.com/fxmorin/carpet-fixes/releases/tag/v1.16.0

**Comment by Rozbiynk** [comment]
wow, thank, now I can dont use carpet fixes, xd
