### ISSUE TITLE
/player X login from QuickCarpet

### ISSUE THREAD

**Issue by lenurem** [TISUnion/Carpet-TIS-Addition#116]
### Motivation

Useful for tree farms with precise location requirements. 
Spawning bots after server restart

### Description

QuickCarpet has this feature where you can spawn bots at their last location by using the "login" feature in /player.

**Comment by Fallen-Breath** [comment]
`rejoin` sounds better than `login` imo, so it will be `/player xxx rejoin`

**Comment by Fallen-Breath** [comment]
I change my mind again xd, `join` might be better and more simple than `rejoin`
