### ISSUE TITLE
1.50.0 cause can't connect on server 1.16.5

### ISSUE THREAD

**Issue by shenjackyuanjie** [TISUnion/Carpet-TIS-Addition#117]
### Bug description

![image](https://github.com/TISUnion/Carpet-TIS-Addition/assets/54507071/e9b8efb7-8807-4030-ab49-13bd0418b820)

![image](https://github.com/TISUnion/Carpet-TIS-Addition/assets/54507071/01caad87-32b6-4e45-92eb-34d72fe03f66)

![image](https://github.com/TISUnion/Carpet-TIS-Addition/assets/54507071/9525248c-6dec-48e2-a617-b1e361a354bb)

### Steps to reproduce

1. have a 1.16.5 fabric server with carpet tis 1.50.0 installed
2. switch on tiscmNetworkProtocol
3. left the server
4. rejoin
5. 
![image](https://github.com/TISUnion/Carpet-TIS-Addition/assets/54507071/7e16fe1d-4c6e-460c-8da0-c3ec7e704b20)
![image](https://github.com/TISUnion/Carpet-TIS-Addition/assets/54507071/20c26d7c-7a3e-4392-9bbb-91e5a4b5cc50)

### Expected behavior

can login

### Actual behavior

can't login

### Relevant logs

```
[Server] [11:11:55] [Server thread/INFO]: [shenjack: ]
[Server] [11:11:55] [Server thread/INFO]: [shenjack: TISCM网络协议 (tiscmNetworkProtocol)]
[Server] [11:11:55] [Server thread/INFO]: [shenjack: TISCM网络协议的开关]
[Server] [11:11:55] [Server thread/INFO]: [shenjack: 分类: [TIS], [TISCM网络协议]]
[Server] [11:11:55] [Server thread/INFO]: [shenjack: 当前值: false (default value)]
[Server] [11:11:55] [Server thread/INFO]: [shenjack: Options: [ true false ]]
[Server] [11:11:57] [Server thread/INFO]: Player shenjack (UUID: a810aab3-078a-3172-a410-2ae40fc1bf82) used command: /carpet tiscmNetworkProtocol true
[Server] [11:11:57] [Server thread/INFO]: [shenjack: tiscmNetworkProtocol: true, [永久更改?]]
[Server] [11:12:00] [Server thread/INFO]: Player shenjack (UUID: a810aab3-078a-3172-a410-2ae40fc1bf82) used command: /carpet setDefault tiscmNetworkProtocol true
[Server] [11:12:00] [Server thread/INFO]: [shenjack: 规则“TISCM网络协议 (tiscmNetworkProtocol)”将会被默认设置为true]
[Server] [11:12:04] [Server thread/INFO]: shenjack lost connection: Disconnected
[Server] [11:12:04] [Server thread/INFO]: shenjack left the game
[Server] [11:12:10] [Server thread/INFO]: shenjack[/192.168.3.45:59145] logged in with entity id 1181 at (161.7348996168212, 71.0, 1648.8687754532518)
[Server] [11:12:10] [Server thread/INFO]: shenjack joined the game
[Server] [11:12:10] [Server thread/INFO]: [STDOUT]: sending loot to shenjack
[Server] [11:12:10] [Server thread/INFO]: shenjack lost connection: Internal Exception: java.lang.NoSuchMethodError: 'java.lang.String net.minecraft.class_2540.method_19772()'
[Server] [11:12:10] [Server thread/INFO]: shenjack left the game
```

### Minecraft version

1.16.5

### Carpet TIS Addition version

1.50.0

### Fabric Carpet version

1.4.44

### Other information

![image](https://github.com/TISUnion/Carpet-TIS-Addition/assets/54507071/466dcdbf-bcb8-4880-9d4b-9c0e83e092b1)

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
Once again, it's caused by using `net.minecraft.util.PacketByteBuf#readString()`, the client-side only method (in mc <1.17), on the server-side

**Comment by Fallen-Breath** [comment]
Try https://github.com/TISUnion/Carpet-TIS-Addition/actions/runs/5864556153, it should work now

**Comment by shenjackyuanjie** [comment]
Fixed!
谢谢狐狸
炭烤狐狸！

**Comment by shenjackyuanjie** [comment]
算了，你发release的时候顺手close吧（
