### ISSUE TITLE
Carpet-TIS-Addition可能导致服务器卡顿

### ISSUE THREAD

**Issue by Sakura1618** [TISUnion/Carpet-TIS-Addition#118]
### Bug description

在运行一段时间后，服务器一直处于高mspt并且时不时掉刻的状态，cpu和内存占用率越来越高。

### Steps to reproduce

在发现服务器卡顿后检查了服务器加载的区块并没有不该出现的实体或者卡服机器
然后使用spark模组进行卡顿分析，服务器的卡顿似乎来自于：
carpet-tis-addition$yeetUpdateSuppressionCrash
再次检查过后确定服务器加载区块内没有更抑相关设备

### Relevant logs

以下为spark模组提供的分析信息（包含设备信息、模组列表/版本、线程分析等）
32小时服务器常态运行分析：https://spark.lucko.me/mc7iFLE3Py
空服状态下服务器运行分析：https://spark.lucko.me/yWSsFFmlec

### Minecraft version

1.18.2

### Carpet TIS Addition version

1.51.0

### Fabric Carpet version

1.4.69

### Other information

此计算机还运行一个同样环境的镜像服，所有配置均与主服相同（配置可在spark报告中查看）。
我不是专业人士提供的信息可能有限甚至不准确，spark的报告包含更多有用的信息。
我目前推测可能是更新抑制防崩服导致的，或者与一些优化模组共用产生冲突。

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
形如 `carpet-tis-addition$yeetUpdateSuppressionCrash` 的函数的功能仅仅是包裹 MC 主循环的调用来捕获更新抑制的异常。这一包裹调用的操作，会使其在性能分析器上显示出与 MC 主循环耗时相同的耗时，但这并非是本模组造成的额外耗时

**Comment by Fallen-Breath** [comment]
对于所述的卡顿分析，建议使用 spark 的火焰图功能来查看是什么有着高占用，而非简单地看调用图中函数的耗时占比

![image](https://github.com/TISUnion/Carpet-TIS-Addition/assets/28978806/c712cfd8-37f4-4398-8f64-b0e7ca9df4c9)

可见，卡顿源是 MC 的区块刻、实体运算、区块卸载
