### ISSUE TITLE
RuntimeException: Mixin transformation of net.minecraft.class_310 failed

### ISSUE THREAD

**Issue by N1zyx3** [TISUnion/Carpet-TIS-Addition#122]
### Bug description

This happens when I start the game, I can't even enter the game. The most interesting thing is that version 1.52.0 works for me, but younger versions do not work #

### Steps to reproduce

1. Launch minecraft

### Expected behavior

launch of Minecraft

### Actual behavior

[Error image](https://drive.google.com/file/d/12AZ7IC53SyjUR_rG3YYiOew3UkDOPigP/view?usp=drive_link)

### Minecraft version

1.20.1

### Carpet TIS Addition version

1.53.0, 1.53.1

### Fabric Carpet version

1.4.112

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
Please give valid information on the issue, e.g. crash logs, not inaccessible image

**Comment by Fallen-Breath** [comment]
Closed as no response and no valid information
