### ISSUE TITLE
[BUG] Minecraft 1.19 .x - 1.20.x Carpe TIS Addition 英文规则列表重复显示

### ISSUE THREAD

**Issue by 1024-byteeeee** [TISUnion/Carpet-TIS-Addition#123]
### Bug description

佛冷你好，因为Carpet AMS Addition也是用的您的代码来做的翻译，发现了这个问题，于是我弄了一个较为纯净的1.20.2的环境并安装了最新的Carpet TIS Addition发现也有这个问题，我目前采用的方式是删除了英文yml翻译文件下所有的name条目。

### Steps to reproduce

1、进入游戏
2、确保carpet语言为英文
3、输入/carpet单击TIS显示Carpet TIS Addition规则列表

### Expected behavior

![2](https://github.com/TISUnion/Carpet-TIS-Addition/assets/77058327/9dccbe90-77df-40a7-a377-2a01e533c34b)

### Actual behavior

![1](https://github.com/TISUnion/Carpet-TIS-Addition/assets/77058327/8df04cc5-9074-4efb-9360-e35858303f46)

### Minecraft version

1.19.x - 1.20.x

### Carpet TIS Addition version

carpet-tis-addition-mc1.20.2-v1.53.1

### Fabric Carpet version

fabric-carpet-1.20.2-1.4.121+v231011

### Other information

以下是我测试的模组列表：
![mods](https://github.com/TISUnion/Carpet-TIS-Addition/assets/77058327/a2fbaf9f-9689-4be0-b5ac-852e250b5f69)

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
意料中的表现，这是 fabric-carpet 的翻译逻辑的预料中表现。如果你认为这是 bug，请向 fabric-carpet 提交 issue

fabric-carpet 相关代码：

https://github.com/gnembon/fabric-carpet/blob/3ab4c326d2d54e52a8b1625a34af17720d42d338/src/main/java/carpet/api/settings/SettingsManager.java#L643-L645 

https://github.com/gnembon/fabric-carpet/blob/3ab4c326d2d54e52a8b1625a34af17720d42d338/src/main/java/carpet/api/settings/RuleHelper.java#L82-L85

**Comment by 1024-byteeeee** [comment]
😀 谢谢你的解答 ！
