### ISSUE TITLE
Fabric 0.15.0 导致崩溃

### ISSUE THREAD

**Issue by zhongbai2333** [TISUnion/Carpet-TIS-Addition#127]
### Bug description

3天前出的fabric 0.15.0与现版本tis addition有兼容问题

### Steps to reproduce

安装 Fabric 0.15.0
安装 tis addition

### Relevant logs

https://mclo.gs/CzbjkbG

### Minecraft version

1.20.1

### Carpet TIS Addition version

1.50.1

### Fabric Carpet version

1.4.112+v230608

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
Related to https://github.com/FabricMC/fabric-loader/pull/812
