### ISSUE TITLE
创造模式无法破坏基岩

### ISSUE THREAD

**Issue by AugustusNirgal** [TISUnion/Carpet-TIS-Addition#128]
### Motivation

创造手滑打掉了基岩，不知道基岩原本的位置，想复原很麻烦

### Description

加入禁止创造玩家破坏基岩的规则

**Comment by Fallen-Breath** [comment]
该功能需求仅仅是针对某种特定场景的需求，并非是一种有价值的通用需求。我不认为所述规则将会是一种低价值的规则，因此不考虑这一功能需求

对于所述，手滑打掉方块无法复原，的问题，应该使用其他的更准确的方案来解决，如：客户端侧的原理图储存、服务端侧的存档备份、服务端侧的操作记录回滚模组等，来实现。这一类方案才是专业对口的解决方案，对于任意方块（不限于基岩）的任意影响（不限于敲方块），都可正确的复原回滚操作

对于具体的，不知基岩原本位置的问题，如果是指自然生成的基岩的话，也可以通过新开同种子存档来参照复原
