### ISSUE TITLE
[1.20.4] Crash when lighting TNT (ClassCastException: class java.lang.Integer cannot be cast to class net.minecraft.class_2680)

### ISSUE THREAD

**Issue by morgantic** [TISUnion/Carpet-TIS-Addition#129]
### Bug description

Minecraft crashes when igniting a TNT block with Carpet-TIS-Addition loaded.

### Steps to reproduce

Get 1.20.4
Install Fabric, carpet and TIS-Addition
open a world (I tested in single player) and ignite a TNT block

### Expected behavior

The game doesn't crash

### Actual behavior

The game crashes reproducible

### Relevant logs

https://mclo.gs/plIO3kO

### Minecraft version

1.20.4

### Carpet TIS Addition version

1.54.3

### Fabric Carpet version

0.15.1

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
Try https://github.com/TISUnion/Carpet-TIS-Addition/actions/runs/7176105247, it should fix the issue

**Comment by morgantic** [comment]
> Try https://github.com/TISUnion/Carpet-TIS-Addition/actions/runs/7176105247, it should fix the issue

Confirmed to work in 1.20.4
Thank you very much for the quick reply!
