### ISSUE TITLE
uuid映射表

### ISSUE THREAD

**Issue by AugustusNirgal** [TISUnion/Carpet-TIS-Addition#132]
### Motivation

服务端正版验证开启和关闭时，玩家id与uuid的映射遵循不同的规则，使得模式切换后无法继承玩家信息。

### Description

建立一个更好的映射表，使得正版验证关闭时，登入的玩家可以根据id获得与正版验证开启时相同的uuid；
或者，允许一个自定义的映射表，使op可以在id与uuid之间建立自定义的映射。

**Comment by Fallen-Breath** [comment]
建议自行实现相关 mod，因为所述需求是与具体运维环境密切相关的，具体环境拥有的上下文信息不同，可实现的功能也有不同。除此之外，正版账号的改名操作也会让所述的 uuid 映射难以维护
