### ISSUE TITLE
[Crash] yeetUpdateSuppressionCrash_implForThreadExecutorTaskExecuting: Found unexpected argument type

### ISSUE THREAD

**Issue by Phoupraw** [TISUnion/Carpet-TIS-Addition#133]
### Bug description

Crash on launching.

### Steps to reproduce

1. Launch.

### Expected behavior

Launch.

### Actual behavior

Crash.

### Relevant logs

[latest.log](https://github.com/TISUnion/Carpet-TIS-Addition/files/13840133/latest.log)

### Minecraft version

1.20.1

### Carpet TIS Addition version

mc1.20.1-v1.55.0

### Fabric Carpet version

1.20-1.4.112+v230608

### Other information

To wrap `super.executeTask(task)` where `this` is `ReentrantThreadExecutor` while `super` is `ThreadExecutor`, should the first param of the handler method be `ReentrantThreadExecutor` or `ThreadExecutor`?

(Fabric loader 0.15 has caused a lot of crash to me in the past few days.)

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
Cannot reproduce with

- `carpet-tis-addition 1.55.0`
- `carpet 1.4.112+v230608`
- `fabricloader 0.15.3`
- `java 17`
- `minecraft 1.20.1`

Please check your mods and figure out which mod causes the issue

**Comment by Fallen-Breath** [comment]
closed as no response
