### ISSUE TITLE
Game crashed when launching with exordium (1.19.4)

### ISSUE THREAD

**Issue by NotEvenBelow** [TISUnion/Carpet-TIS-Addition#134]
modlist: 
![image](https://github.com/TISUnion/Carpet-TIS-Addition/assets/104668131/e5479cf4-3afe-4a13-821a-9def30894477)

log: 
[latest.log](https://github.com/TISUnion/Carpet-TIS-Addition/files/13844195/latest.log)

- this isnt duplicated pretty sure

**Comment by Fallen-Breath** [comment]
exordium mod shadows MixinExtras without relocates its package, resulting a same behavior as issue #121

See also this comment: https://github.com/TISUnion/Carpet-TIS-Addition/issues/121#issuecomment-1806839438

I'll suggest to report this issue to exordium

**Comment by NotEvenBelow** [comment]
https://github.com/tr7zw/Exordium/issues/129

**Comment by NotEvenBelow** [comment]
this mod now crashing with other mods too not just exordium
[crash-2024-01-06_16.35.24-client.txt](https://github.com/TISUnion/Carpet-TIS-Addition/files/13848991/crash-2024-01-06_16.35.24-client.txt)
[latest.log](https://github.com/TISUnion/Carpet-TIS-Addition/files/13848992/latest.log)

**Comment by Fallen-Breath** [comment]
> this mod now crashing with other mods too not just exordium [crash-2024-01-06_16.35.24-client.txt](https://github.com/TISUnion/Carpet-TIS-Addition/files/13848991/crash-2024-01-06_16.35.24-client.txt) [latest.log](https://github.com/TISUnion/Carpet-TIS-Addition/files/13848992/latest.log)

Not related to this issue, and duplicated of #127

**Comment by NotEvenBelow** [comment]
Downgrading the loader to 0.14.25 seem to fix everything i hate my life ❤❤❤❤
