### ISSUE TITLE
[功能请求] 结构方块范围限制 (structureBlockLimit) 高版本支持

### ISSUE THREAD

**Issue by ailixluo** [TISUnion/Carpet-TIS-Addition#135]
### Motivation

 你好，1.18以上没有跟进更新，就算结构方块范围调到256以上，比如1000，实际上也就只有256的边长。

### Description

我希望 结构方块范围限制 (structureBlockLimit) 可以支持到384边长。

**Comment by Fallen-Breath** [comment]
1.16 以上的 `structureBlockLimit` 由 fabric carpet 实现，并非本 mod 实现。请向 fabric carpet 提 issue
