### ISSUE TITLE
tick指令carpet化的功能仍然有缺失

### ISSUE THREAD

**Issue by acaciachan** [TISUnion/Carpet-TIS-Addition#138]
### Bug description

<img width="334" alt="0236a26c1b5ecb69002fcf707663ca61" src="https://github.com/TISUnion/Carpet-TIS-Addition/assets/73088428/a2ba7649-2b6d-40c3-bc75-47cd6b180ee4">
tick类指令carpet化不完善，以前carpet的时候输入"/tick warp"，后面不接数字或者接个0，效果等同于现在的/tick sprint stop。这也是旧版的停止加速的方式，而且一般停止加速都是越快越好，更短的指令这方面也更有优势。

### Steps to reproduce

1

### Minecraft version

all

### Carpet TIS Addition version

latest

### Fabric Carpet version

0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
这涉及到了修改指令树结构，需要在原版创建指令树的时候进行修改，指令树创建完后就不好改了。麻烦点是，fabric-carpet 加载配置文件的时机太迟了，比原版创建指令树的时间点迟……

如果要解决的话，下面有两个可能算是方案的思路：

1. 想办法让配置文件加载地更早些，得确保不能影响其他 carpet（拓展）的运行
2. 想办法动态修改指令树。得确保没有副作用，感觉有点难

**Comment by acaciachan** [comment]
这个不好弄，那就在tweakermore里实现吧，close
