### ISSUE TITLE
Many messages spamming the log in version1.57.0

### ISSUE THREAD

**Issue by enbyd** [TISUnion/Carpet-TIS-Addition#139]
### Bug description

When logged on to a server running CarpetTIS, with CarpetTIS 1.57.0 also installed on the client, the following lines are output to the log during player movement each tick, which quickly increases the log file size:
```
[Netty Epoll Client IO #0/INFO]: CarpetNetworkProtocolRewriter rewrite start, target=V1
[Netty Epoll Client IO #0/INFO]: UniversalCarpetPayload read V1 success, action=1 str=null nbt={TickPlayerActiveTimeout:2}
```

### Steps to reproduce

Install Carpet Mod 1.4.57 and CarpetTIS 1.57.0 (and any direct dependencies) on a dedicated server.
Install Carpet Mod 1.4.57 and CarpetTIS 1.57.0 (and any direct dependencies) on the client.
Log on to the server and move around while not in fly mode (or have another player move around while not in fly mode).
Observer the lines printed to the output log.

### Expected behavior

No log spam

### Actual behavior

Log spam

### Minecraft version

1.17.1

### Carpet TIS Addition version

1.57.0

### Fabric Carpet version

1.4.57

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
why didn't I cleanup all those debug codes... fixing
