### ISSUE TITLE
活板门不再抖掉红石原件

### ISSUE THREAD

**Issue by acaciachan** [TISUnion/Carpet-TIS-Addition#144]
### Motivation

活板门会把各种红石原件，例如中继器，比较器，压力板等等再开启的时候抖掉

### Description

1

### Other information

1

**Comment by Fallen-Breath** [comment]
活板门抖掉压力板是自至少 1.14.4 以来就有的表现；抖掉红石粉、中继器、比较器，是 23w35a（1.20.2 快照）引入的机制。先只给后者做个规则给撤销吧
