### ISSUE TITLE
[Feature Request] change in blockPlacementIgnoreEntity rule

### ISSUE THREAD

**Issue by peow** [TISUnion/Carpet-TIS-Addition#147]
### Motivation

the **blockPlacementIgnoreEntity** rule is very useful, I like it a lot, but only when it's to place blocks in the same place as other entities, such as animals and mobs, but being able to place blocks in the same place as I am bothers me, for example, when creating a pillar in creative, the block can be placed inside my character and I fall off the pillar

### Description

I think it would be interesting to separate this rule into:
0- disabled
1- only other entities (mobs/animals/other players)
2- all entities (even yourself)

**Comment by Fallen-Breath** [comment]
Being able to place blocks in the same place as the player is an intended behavior. If you're in creative mode and want to build a pillar, you can just fly
