### ISSUE TITLE
java.lang.NoSuchMethodError: 'int net.minecraft.class_1767.method_16357()' in SupplierCounter module

### ISSUE THREAD

**Issue by hxy123abc** [TISUnion/Carpet-TIS-Addition#148]
### Bug description

I upgraded the mod from 1.58.0 to 1.59.2 for a dedicated server, and it failed to launch. This did not happen when I was using version 1.58.0.

### Steps to reproduce

1. Launch a dedicated server with carpet, tis carpet and fabric API.
2. Wait for the crash.

### Expected behavior

The server should launch.

### Actual behavior

The server crashed with exception java.lang.NoSuchMethodError: 'int net.minecraft.class_1767.method_16357()'.

### Relevant logs

[latest.log](https://github.com/TISUnion/Carpet-TIS-Addition/files/15415772/latest.log)

### Minecraft version

1.16.5

### Carpet TIS Addition version

1.59.2

### Fabric Carpet version

1.4.44

### Other information

The suspisious method `net.minecraft.class_1767.method_16357()` is `net.minecraft.util.DyeColor.getSignColor()` in mapping yarn-1.16.5+build.10-v2. Fabric version is 0.15.11. I have not tested this on a mc client or other fabric versions though. I guess it will crash too.

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
Oh no `DyeColor.getSignColor()` is client-side only in 1.16.5

**Comment by Fallen-Breath** [comment]
Fixed in v1.59.3
