### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by se3ya** [TISUnion/Carpet-TIS-Addition#152]
### Bug description

Game crashes when starting the game. Removing mod fixes crash issue.

### Steps to reproduce

1. Download mod Carpet, Carpet Shadow, Carpet TIS Addition. 2. Start the game
Carpet Shadow - 1.10.2 version

### Relevant logs

https://pastebin.com/7yY4PrXF 

### Minecraft version

1.20.1

### Carpet TIS Addition version

1.59.4

### Fabric Carpet version

1.4.112

### Other information

Starting game with Carpet Fixes (idk if it helps you) gives this log:
https://pastebin.com/pKHsxRL8

---

Starting game with my main Modpack:
https://pastebin.com/QAmUGF2T

### Check list

- [x] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
Cannot reproduce with carpet-shadow [v1.10.2-MC1.20.1-HotFix-2](https://github.com/mattymatty97/carpet-shadow/releases/tag/v1.10.2-MC1.20.1-Hotfix). Possible duplicated with #121

**Comment by se3ya** [comment]
I had ''carpet-shadow-1.10.2-MC1.20.1+ build 3'' and now tried with [v1.10.2-MC1.20.1-HotFix-2](https://github.com/mattymatty97/carpet-shadow/releases/tag/v1.10.2-MC1.20.1-Hotfix) and it worked! But only it crashes with carpet-fixes-1.20-1.17.0. But yeah thanks!

**Comment by se3ya** [comment]
Okay I fixed crashing with carpet fixes by downloading v1.16.1.
