### ISSUE TITLE
[Crash] May conflict with the 1.21 lithium mod?

### ISSUE THREAD

**Issue by disymayufei** [TISUnion/Carpet-TIS-Addition#154]
### Bug description

When I try to install the tis addtion with the lithium latest version, the game was crashed while loading.

### Steps to reproduce

1. Install the Fabric Loader version 0.15.11, with the Fabric API(version 0.100.1+1.21)
2. Install this mod(version mc1.21-rc1-v1.59.4) with the carpet mod(version 1.21-1.4.147+v240613)
3. Install and enable the lithium mod(version mc1.21-0.12.5) at the same time
4. Try to start the game, and then the game crashed, with the log you can see at the "Relevant logs" part

### Relevant logs

https://pastebin.com/DMTy0tW2

### Minecraft version

1.21

### Carpet TIS Addition version

mc1.21-rc1-v1.59.4

### Fabric Carpet version

1.21-1.4.147+v240613

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by disymayufei** [comment]
By the way, the bug will be happened on both client and server

**Comment by Fallen-Breath** [comment]
Please wait for release version of carpet-tis-addition for MC 1.21

**Comment by disymayufei** [comment]
ok, thx

**Comment by Fallen-Breath** [comment]
[v1.60.0](https://github.com/TISUnion/Carpet-TIS-Addition/tree/v1.60.0) is release without the described lithium confliction
