### ISSUE TITLE
how do i remove this chat messenge 

### ISSUE THREAD

**Issue by TheDanichDude** [TISUnion/Carpet-TIS-Addition#155]
### Bug description

![Skærmbillede 2024-06-19 142356](https://github.com/TISUnion/Carpet-TIS-Addition/assets/173268112/7a0ccbec-6b73-4d90-b4b7-e25e4a39afed)
how do i remove this 
i cant see anything in my chat 

### Steps to reproduce

i do not know what to do 

### Minecraft version

1.20.6

### Carpet TIS Addition version

1.59.4

### Fabric Carpet version

1.4.147

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
You subscribed the damage logger. Enter `/log damage clear` to unsubscribe from it

**Comment by TheDanichDude** [comment]
thanks
