### ISSUE TITLE
[suggestion] Log XP orb values in chat

### ISSUE THREAD

**Issue by CodeF53** [TISUnion/Carpet-TIS-Addition#16]
I would like to use the /log xporb command to measure XP/hour.

As of now, looking at chat logs, an xp orb event looks like this:
`[22:14:48] [main/INFO]: [CHAT] [794976] Experience Orb created @ [127.3, 31.0, 246.3] $`

Desired function:
`[22:14:48] [main/INFO]: [CHAT] [794976] Experience Orb of value N created @ [127.3, 31.0, 246.3] $`

This would allow an external program to be used to scrape chat logs to measure xp/h

**Comment by Fallen-Breath** [comment]
Currently lifetime tracker is able to count the amount of xp per hour, i guess it meets your need

![image](https://user-images.githubusercontent.com/28978806/108616530-07f71500-7449-11eb-998c-1d5f6b2a035f.png)

It's added in [v1.13.0](https://github.com/TISUnion/Carpet-TIS-Addition/releases/tag/v1.13.0)

**Comment by CodeF53** [comment]
Thanks!
