### ISSUE TITLE
/ping指令无法使用

### ISSUE THREAD

**Issue by snpdzk** [TISUnion/Carpet-TIS-Addition#161]
### Bug description

![image](https://github.com/user-attachments/assets/328c0188-db02-41d6-87d6-32e24ebba399)

### Steps to reproduce

无

### Relevant logs

服务端日志：https://mclo.gs/GOpqwBy

### Minecraft version

1.18.2

### Carpet TIS Addition version

1.60.0

### Fabric Carpet version

1.4.69

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
与本 mod 无关。本 mod 不提供 `/ping` 指令
