### ISSUE TITLE
[bug]  在minecraft1.21中启用规则optimizedTNT会导致风弹造成方块破坏

### ISSUE THREAD

**Issue by vocaloidkiss** [TISUnion/Carpet-TIS-Addition#164]
如上所述，在minecraft1.21中，加载Carpet TIS Addition v1.61后启用规则optimizedTNT，会导致风弹造成方块破坏

**Comment by Fallen-Breath** [comment]
fabric-carpet 的 bug，与本 mod 无关

见 https://github.com/gnembon/fabric-carpet/issues/1928
