### ISSUE TITLE
Player can't enter the server on 1.51.0+ version ERROR: Internal Exception: io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0

### ISSUE THREAD

**Issue by LSCube7** [TISUnion/Carpet-TIS-Addition#167]
### Bug description

对于所有有自己网络协议的Carpet附属，包括但不限于Carpet TIS Addition和其他友商的产品，在支持1.20.2版本后，玩家用1.20.1进入服务器，均会导致服务器报错：Internal Exception: io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0，玩家无法连接。推测是1.20.2的网络协议没有向下兼容而mod使用新版的网络服务器。

### Steps to reproduce

1. 启动带有Carpet TIS Additon的1.20.1服务器
2. 使用客户端连接服务器

### Expected behavior

进入服务器

### Actual behavior

Internal Exception: io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0

### Relevant logs

https://pastebin.com/7ZCqEhea

### Minecraft version

1.20.1

### Carpet TIS Addition version

1.62.0

### Fabric Carpet version

1.4.112

### Other information

只在mod同时支持1.20.2的版本后才会触发

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
无法复现。MC 1.20.1 客户端可正常进入 MC 1.20.1 / MC 1.20.2 服务端，环境如下

## 1.20.1 客户端 -> 1.20.1 服务端

客户端、服务端：

- carpet 1.4.112+v230608
- carpet-tis-addition 1.62.0

## 1.20.1 客户端 -> 1.20.2 服务端

客户端：

- MC 1.20.1
- carpet 1.4.112+v230608
- carpet-tis-addition 1.62.0

服务端：

- MC 1.20.2
- carpet 1.4.121+v231011
- carpet-tis-addition 1.62.0

代理端（关闭正版验证、`player-info-forwarding-mode = "none"`）：

- Velocity 3.3.0
- ViaVersion-5.0.3-SNAPSHOT
- ViaBackwards-5.0.3-SNAPSHOT
- ViaRewind-4.0.2

**Comment by Fallen-Breath** [comment]
除此之外，MC 1.20.1 客户端也可正常进入 MC1.20.1 服务端，服务端、客户端环境如下（同 https://github.com/TISUnion/Carpet-TIS-Addition/issues/167#issuecomment-2274058457 )

- carpet 1.4.112+v230608
- carpet-tis-addition 1.62.0

**Comment by LSCube7** [comment]
emm... 现在确实没问题了，我2月份的时候测试时只留了carpet-TIS-addition 0.56.1，报了相同的错，所以以为这次也是这里的问题，非常抱歉~
