### ISSUE TITLE
是否有计划添加声音更新抑制器的相关规则

### ISSUE THREAD

**Issue by PPGC777** [TISUnion/Carpet-TIS-Addition#169]
### Motivation

添加声音更新抑制器的相关规则

### Description

比如在1.21之后版本重新引入陷阱箱IAE更新抑制(TrappedChestIAEReintroduced)
顺便在yeetUpdateSuppressionCrash规则中增加阻止因"IllegalArgumentException"异常的崩溃

**Comment by Fallen-Breath** [comment]
见 #165

**Comment by Fallen-Breath** [comment]
对于”比如在1.21之后版本重新引入陷阱箱IAE更新抑制(TrappedChestIAEReintroduced)“，这并不容易实现，因为 mojang 在 1.21.1 修复的是整个方块实体替换的可行性

**Comment by PPGC777** [comment]
> 对于”比如在1.21之后版本重新引入陷阱箱IAE更新抑制(TrappedChestIAEReintroduced)“，这并不容易实现，因为 mojang 在 1.21.1 修复的是整个方块实体替换的可行性

瞄了一眼Carpet ORG Addition的简易CCE, 在支持1.21.1及后续的版本中 直接抛出CCE异常来实现的.
大概要将1.21.1及以上的版本恢复之前的实体替换需要动刀的地方有点多, 不知道如果只根据某些游戏中的行为来直接抛出异常并进行更新抑制来模拟IAE更新抑制机制是否有可行性.

**Comment by Fallen-Breath** [comment]
> 只根据某些游戏中的行为来直接抛出异常并进行更新抑制来模拟IAE更新抑制机制是否有可行性

如果你只想要一个抛出 IAE 异常的方法，用于创造模式测试等，规则 updateSuppressionSimulator 已支持

**Comment by PPGC777** [comment]
> 如果你只想要一个抛出 IAE 异常的方法，用于创造模式测试等，规则 updateSuppressionSimulator 已支持

更主要的目的还是恢复实体替换的机制, 用以在高版本的游戏中做出声音抑制器(这款抑制器的范围抑制还是比传统抑制器+bud链有些许方便的). 

>不知道如果只根据某些游戏中的行为来直接抛出异常并进行更新抑制来模拟IAE更新抑制机制是否有可行性.

或者, 参照ORG扩展的简易CCE实现方式, 在范围内检测特定名称的陷阱箱及红石信号强度, 然后抛出IAE异常并根据信号强度给出对应的抑制效果, 伪装成一个声音抑制器.

看到合并#186, 希望有后续进展.

**Comment by Fallen-Breath** [comment]
> 更主要的目的还是恢复实体替换的机制

见 https://github.com/TISUnion/Carpet-TIS-Addition/issues/169#issuecomment-2282695164

> 或者, 参照ORG扩展的简易CCE实现方式, 在范围内检测特定名称的陷阱箱及红石信号强度, 然后抛出IAE异常并根据信号强度给出对应的抑制效果, 伪装成一个声音抑制器.

不考虑。这已经属于是自定义的非原版特性了，因为它完全是 mod 自行定义的一个机制，并未与某个 mc 版本的原版机制对齐

**Comment by PPGC777** [comment]
> 不考虑。这已经属于是自定义的非原版特性了，因为它完全是 mod 自行定义的一个机制，并未与某个 mc 版本的原版机制对齐

了解, 更赞同恢复原版的实体替换机制. 期待后续更新.

**Comment by PPGC777** [comment]
> 对于”比如在1.21之后版本重新引入陷阱箱IAE更新抑制(TrappedChestIAEReintroduced)“，这并不容易实现，因为 mojang 在 1.21.1 修复的是整个方块实体替换的可行性

经人提示, 有字母哥([Earthcomputer](https://github.com/Earthcomputer))做了一个在1.21.1的恢复实体替换mod(`https://github.com/Earthcomputer/update-depression/tree/1.21.1/`)
该mod可以实现`/cconfig updatedepression allowInvalidBlockEntities`, `/cconfig updatedepression reintroduceCCESuppression`, `/cconfig updatedepression updateSuppressionCrashFix`, 以及通过`/setnoisesuppressor posX posY posZ`, `/setsuppressedshulkerbox posX posY posZ`这两个指令来直接放置CCE和IAE. 这个mod所用代码是否对在>=1.21.1版本的重新引入实体替换有所帮助?

**Comment by Fallen-Breath** [comment]
没有帮助，因为所述 mod 的实现方式即为我不想做的实现方式

**Comment by PPGC777** [comment]
> 没有帮助，因为所述 mod 的实现方式即为我不想做的实现方式

弱弱问一句, 该mod的方式是直接跳过方块实体类型的检测还是什么其他的方式?

另外, 1.20.2以上的版本, mojang是不是修改了熔炉的更新顺序(之前貌似是先爆出经验 然后接受比较器更新, 从而用CCE做到挖掘熔炉 放置熔炉来获得经验, 有没有什么方法可以把熔炉恢复到1.20.1的表现.)

**Comment by Fallen-Breath** [comment]
`Earthcomputer/update-depression` 做了这两件事：

1. 重新引入了方块实体不匹配的潜影盒的 CCE 触发点。此功能 `shulkerBoxCCEReintroduced` 规则已实现
2. 跳过了几个 mc1.21.1+ 的，方块实体替换的检测。这里也是我在 https://github.com/TISUnion/Carpet-TIS-Addition/issues/169#issuecomment-2282695164 里所提及的担心点。要引入本 mod 的话，相关改动需要确定清楚完备性以及影响范围才行，这需要时间

对于其他问题，一个 issue 做一件事

**Comment by PPGC777** [comment]
> 2. 跳过了几个 mc1.21.1+ 的，方块实体替换的检测。这里也是我在 [是否有计划添加声音更新抑制器的相关规则 #169 (comment)](https://github.com/TISUnion/Carpet-TIS-Addition/issues/169#issuecomment-2282695164) 里所提及的担心点。要引入本 mod 的话，相关改动需要确定清楚完备性以及影响范围才行，这需要时间

这个mod确实还是有些问题的, 比如在仅开启`/cconfig updatedepression allowInvalidBlockEntities`后, 通过`/setnoisesuppressor posX posY posZ`摆放的蜂巢 陷阱箱 熔炉等可以是IAE更新抑制器, 但是通过其他更新抑制器来制作IAE时会失败, 执行`/data get block`后发现实体替换并没有成功(但是制作CCE时, 实体替换是可以成功的). 

期待完美的方案和规则引入.

**Comment by PPGC777** [comment]
> 对于其他问题，一个 issue 做一件事

`New issue` -> `Feature Request` 好像有点问题, `Create`按钮点不动, 尝试过PC和手机端都不行.
Chrome控制台提示
````
popover.js:368 Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': 'dialog:modal, [role="dialog"][aria-modal="true"]' is not a valid selector.
    at HTMLDocument.value [as querySelectorAll] (https://github.githubassets.com/assets/vendors-node_modules_oddbird_popover-polyfill_dist_popover_js-9da652f58479.js:1:4659)
    at https://github.githubassets.com/assets/ui_packages_ui-commands_ui-commands_ts-2d52c8e72e64.js:1:18044
    at https://github.githubassets.com/assets/ui_packages_ui-commands_ui-commands_ts-2d52c8e72e64.js:1:18280
    at https://github.githubassets.com/assets/ui_packages_ui-commands_ui-commands_ts-2d52c8e72e64.js:1:18389
    at HTMLDocument.e (https://github.githubassets.com/assets/ui_packages_ui-commands_ui-commands_ts-2d52c8e72e64.js:1:18834)
    at triggerCommand (https://github.githubassets.com/assets/ui_packages_ui-commands_ui-commands_ts-2d52c8e72e64.js:1:19190)
    at onClick (https://github.githubassets.com/assets/ui_packages_ui-commands_ui-commands_ts-2d52c8e72e64.js:1:20471)
    at Object.eD (https://github.githubassets.com/assets/react-lib-1622bd1e542f.js:25:14919)
    at eA (https://github.githubassets.com/assets/react-lib-1622bd1e542f.js:25:15073)
    at https://github.githubassets.com/assets/react-lib-1622bd1e542f.js:25:33389
````

**Comment by Fallen-Breath** [comment]
github 的问题问 github 去，建议检查浏览器环境和网络条件，同时这与本 issue 也无关
