### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by srnyx** [TISUnion/Carpet-TIS-Addition#17]
Server crashes when using the latest version of Carpet TIS Addition and regular Carpet on 1.16.5.
https://pastebin.com/wHLt95r6

_Downgrading to an earlier Carpet TIS Addition fixed it and the server didn't crash._

**Comment by Fallen-Breath** [comment]
Please upload the full server log or show what mods u have installed, since it works fine for me with only carpet mods

**Comment by srnyx** [comment]
> Please upload the full server log or show what mods u have installed, since it works fine for me with only carpet mods

Log (it stops right before the crash error thing): https://pastebin.com/FBkCY74h
Mods (may not be all of them as I'm using /mods, a command from another mod [if there is another way to get a list of the mods, let me know]): https://pastebin.com/jQ212h6v

**Comment by Fallen-Breath** [comment]
Man that's tons of mods, I will suggested u to figure out which mod that causes the conflict

Temporary fix: edit `carpet-tis-addition.mixins.json` in the .jar and remove the line `rule.creativeOpenContainerForcibly.ChestBlockMixin`, which will disable the funtionality of rule `creativeOpenContainerForcibly` for chest

**Comment by srnyx** [comment]
> Man that's tons of mods, I will suggested u to figure out which mod that causes the conflict
> 
> Temporary fix: edit `carpet-tis-addition.mixins.json` in the .jar and remove the line `rule.creativeOpenContainerForcibly.ChestBlockMixin`, which will disable the funtionality of rule `creativeOpenContainerForcibly` for chest

If it's something with chests, I have ExpandedStorage and InventorySorter installed.

**Comment by Fallen-Breath** [comment]
> If it's something with chests, I have ExpandedStorage and InventorySorter installed.

Try minimize the amount of mods that can cause the crash

**Comment by Fallen-Breath** [comment]
Ok i found an issue... yarn doesn't like the method `net.minecraft.block.ChestBlock#getBlockEntitySource` and doesn't provide a intermediary mapping for this method at dedicated server run time, so the injection failed
