### ISSUE TITLE
1.63版本假人在声音更新抑制范围内右键展示框的一些问题

### ISSUE THREAD

**Issue by PPGC777** [TISUnion/Carpet-TIS-Addition#170]
### Bug description

在声音更新抑制器范围内 使用假人对着展示框右键`use once`或者`use interval X`等操作时, 触发IAE异常, 防崩服`yeetUpdateSuppressionCrash`规则起效后, 假人貌似会认为`use once`失败 然后再次执行`use once`, 看上去就像假人在执行间隔1gt的右键操作.
在假人执行`use`操作时, 加入玩家左键单击操作虽然可以成功复制展示框内物品 但是复制的物品无法被玩家拾取; 复制的物品可以被下方漏斗矿车吸取, 但是漏斗矿车下方的漏斗无法吸取漏斗矿车内物品. 
这个bug大概并不是carpet TIS addition的防崩溃规则引起, 是否有修复方法.

### Steps to reproduce

![}5O482G2I9(Z%1LP 4V4L3T](https://github.com/user-attachments/assets/a40b277c-8696-4f4c-befa-567156dc3916)
假人如图所示站位: 
假人hsds执行`/player hsds use once`, 表现为手中物品在展示框内转圈;
假人hsdd执行`/player attack interval 100`, 无反应
![B_~BQ@ZSQJ8AS08@JL~EQFW](https://github.com/user-attachments/assets/60c344f4-be10-487f-9704-8d2de20605cb)
漏斗矿车和漏斗链如图放置

### Expected behavior

根据purpur 1.20.2端的假人测试, 应该是假人A在向展示框放入物品, 假人B随后取出展示框物品, 理论上可以做到1gt放 1gt取;
同时被复制的物品能被拾取或是被下方的漏斗链和漏斗矿车吸走.

### Actual behavior

假人A不断向展示框右键, 假人B无动于衷
假人在执行指令时, 真人玩家无法拾取复制的物品

漏斗矿车可以吸取复制的物品
漏斗矿车下的漏斗链无法吸取上方漏斗矿车内物品

### Minecraft version

1.20.1

### Carpet TIS Addition version

1.63

### Fabric Carpet version

1.4.112

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
这种非原版的功能（假人右键）在抛异常的更新抑制的场景下，出现任何与真实玩家操作不一致的行为，都是可能的。建议去向 fabric carpet 侧反馈，比如对于 use once，先清空 action pack 计数器，再去实际执行操作。不过我觉得 fabric carpet 也不一定会修这个问题，毕竟在更新抑制抛异常的场景下，一切都是未定义行为
