### ISSUE TITLE
HopperHelper Mixin Carpet TIS Addions Crash

### ISSUE THREAD

**Issue by TinyDerp** [TISUnion/Carpet-TIS-Addition#171]
### Bug description

The server crashes a millisecund a player joins.

### Steps to reproduce

1. Start the server
2. Join the server
3. See the light for a split second
4. Crash

### Expected behavior

That there isn't a crash

### Actual behavior

There is a crash

### Relevant logs

[crash-2024-08-15_20.08.08-server.txt](https://github.com/user-attachments/files/16627981/crash-2024-08-15_20.08.08-server.txt)

### Minecraft version

1.21

### Carpet TIS Addition version

carpet-tis-addition-v1.63.0-mc1.21.1

### Fabric Carpet version

fabric-carpet-1.21-1.4.147+v240613

### Other information

It seams that Carpet TIS Addions donsn't work with [Lithium](https://github.com/CaffeineMC/lithium-fabric) (lithium-fabric-mc1.21-0.13.0) at all on the newer minecraft versions. Something to do with hoppers and other containers.
I already made the same issue on [Lithium](https://github.com/CaffeineMC/lithium-fabric/issues/553) and they rederected me to here.
Also [Carpet Essentials](https://modrinth.com/mod/essentialaddons) has the same issue.

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by TinyDerp** [comment]
### Minecraft Save if Needed

>[a32xse.zip](https://files.catbox.moe/a32xse.zip)

**Comment by Fallen-Breath** [comment]
known issue

**Comment by Fallen-Breath** [comment]
Fixed in v1.63.1
