### ISSUE TITLE
ai_tracker 范围提示框显示异常问题

### ISSUE THREAD

**Issue by mcxjj** [TISUnion/Carpet-TIS-Addition#172]
### Bug description

TIS扩展包可能导致了使用/ai_tracker villager iron_golem_spawning 时，村民对铁傀儡的检测范围（白框）无法显示，我将TIS-Addtion移出mod后恢复正常
[原carpet官方反馈贴](https://github.com/gnembon/fabric-carpet/issues/1979)

### Steps to reproduce

1. 刷出一些村民
2. /script load ai_tracker
3. /ai_tracker villager iron_golem_spawning

### Expected behavior

能够正常显示铁傀儡识别范围

### Minecraft version

1.21

### Carpet TIS Addition version

1.62.0&1.63.0

### Fabric Carpet version

fabric-carpet-1.21-1.4.147+v240613.jar

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
已确认 bug，scShapes 请求包里的 text label 及之后的 scarpet shape 均无法渲染。影响 MC 1.20.5+
