### ISSUE TITLE
carpet tis一放置漏斗就会崩溃

### ISSUE THREAD

**Issue by Spturate** [TISUnion/Carpet-TIS-Addition#173]
### Bug description

如果搭配锂mod就会出现此bug。只要加载到漏斗游戏立马崩溃

[latest.log](https://github.com/user-attachments/files/16646331/latest.log)

### Steps to reproduce

1.放置漏斗
2.游戏崩溃

### Relevant logs

[latest.log](https://github.com/user-attachments/files/16646332/latest.log)

### Minecraft version

1.21

### Carpet TIS Addition version

1.63.0

### Fabric Carpet version

1.4.147

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
与 #171 重复
