### ISSUE TITLE
1.21最新版tis addition和锂冲突

### ISSUE THREAD

**Issue by AbroadSphere** [TISUnion/Carpet-TIS-Addition#174]
### Bug description

v1.63.1 for mc 1.21.1跟锂冲突

### Steps to reproduce

https://mclo.gs/0HgisrD 这个是崩溃报告

### Minecraft version

1.21

### Carpet TIS Addition version

1.63.1

### Fabric Carpet version

1.21-1.4.147+v240613

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
fabric carpet 的问题，与本 mod 无关

参见：https://github.com/gnembon/fabric-carpet/issues/1973
