### ISSUE TITLE
希望添加类似于carpet 1.4.143 (24w09a-24w11a)之前的潜影盒堆叠实现方式的潜影盒堆叠功能

### ISSUE THREAD

**Issue by MarcoGao123** [TISUnion/Carpet-TIS-Addition#175]
### Motivation

在此版本后的carpet中潜影盒会一直堆叠,即和正常可堆叠物品表现形式类似 包括在通过漏斗漏至的容器中将能堆叠. 所以这会带来很多麻烦 例如打包机的空盒补充的漏斗链需要正常的64倍的盒子才能正常运作. 

### Description

希望实现类似于carpet在此版本之前的潜影盒堆叠 即只有丢到地上时才能堆叠, 当堆叠的潜影盒丢在漏斗上时, 漏斗虽然会以堆叠的方式吸入 但漏斗漏向指向的容器中时潜影盒不会堆叠. 谢谢

**Comment by Fallen-Breath** [comment]
建议去 fabric-carpet 侧反馈，因为这是与 fabric-carpet 新版本相关的需求
