### ISSUE TITLE
启用 optimizedTNT 产生的与风弹有关的bug

### ISSUE THREAD

**Issue by EEpier** [TISUnion/Carpet-TIS-Addition#176]
### Bug description

启用optimizedTNT后会使玩家使用的风弹、发射器发射的风弹、狂风人发射的风弹在落地点产生爆炸. 具有爆炸的伤害, 并且能破坏硬度较低的方块

### Steps to reproduce

1.创建世界
2.打开 optimizedTNT 功能
3.使用风弹

### Minecraft version

1.21

### Carpet TIS Addition version

1.62.0

### Fabric Carpet version

1.4.147+v240613

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
与 #164 重复
