### ISSUE TITLE
1.21.1 与 Lithium v0.14.0 同时安装时引发崩溃

### ISSUE THREAD

**Issue by LuLuLuOfficial** [TISUnion/Carpet-TIS-Addition#178]
### Bug description

貌似与锂不兼容

### Steps to reproduce

版本: Fabric v1.21.1

ModList: 
Lithium v0.14.0
Carpet-TIS-Addition v1.63.2 or v1.62.0
FabricAPI v0.105.0

### Expected behavior

正常启动服务器进程

### Actual behavior

崩溃

### Relevant logs

https://mclo.gs/qc9MeUO

### Minecraft version

1.21.1

### Carpet TIS Addition version

1.63.2

### Fabric Carpet version

0.105.0

### Other information

版本: Fabric v1.21.1

ModList: 
锂 v0.14.0
Carpet-TIS-Addition v1.63.2 or v1.62.0
FabricAPI v0.105.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
已知问题，请暂时不要使用 v0.14.0 的 lithium mod

如确实需使用 lithium > v0.14.0，请使用来自 [misc/lithium-0.14.0](https://github.com/TISUnion/Carpet-TIS-Addition/tree/misc/lithium-0.14.0) 分支的构建，如 https://github.com/TISUnion/Carpet-TIS-Addition/actions/runs/11372076293

**Comment by Fallen-Breath** [comment]
迄今为止，lithium v0.14.0 仍处于实验性的 beta 状态，且本 mod 对其的兼容性改动与较低版本的 lithium mod 是互斥的，因此 [misc/lithium-0.14.0](https://github.com/TISUnion/Carpet-TIS-Addition/tree/misc/lithium-0.14.0) 分支的修改暂时不会合入主线 + 发布

**Comment by LuLuLuOfficial** [comment]
好的好的，感谢回答
