### ISSUE TITLE
在1.21.3版本，Carpet TIS Addition v1.64.2与锂v0.14.1不兼容

### ISSUE THREAD

**Issue by SuanOrange** [TISUnion/Carpet-TIS-Addition#181]
### Bug description

Carpet TIS Addition v1.64.2 for 1.21.3与锂v0.14.1不兼容

### Steps to reproduce

1.安装Carpet TIS Addition v1.64.2 for 1.21.3与lithium fabric-0.14.1-snapshot+mc1.21.3-build.89
2.启动游戏，发现不兼容

### Expected behavior

可以兼容，成功启动游戏

### Actual behavior

游戏无法启动，显示错误报告，提示不兼容

### Relevant logs

https://mclo.gs/yVAYBIo

### Minecraft version

1.21.3

### Carpet TIS Addition version

1.64.2

### Fabric Carpet version

1.4.158+v241022

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [x] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
意料中的行为。与 #178 重复
