### ISSUE TITLE
1.21 | conflicts with lithium

### ISSUE THREAD

**Issue by pivoland** [TISUnion/Carpet-TIS-Addition#185]
### Bug description

 lithium > 0.13.1 not anviable on 1.21, so Carpet TIS Addition v1.65.0 break modpack. Can you return compatibility with it pls?

### Steps to reproduce

Fabric 1.21

### Minecraft version

1.21

### Carpet TIS Addition version

1.65.0

### Fabric Carpet version

1.4.77

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
No. Lithium made a [breaking change](https://github.com/TISUnion/Carpet-TIS-Addition/commit/659c909c784c773a7851a42b59c9747eccc15961), so the same as this mod

**Comment by Fallen-Breath** [comment]
Actually lithium for mc1.21.1 works in mc1.21. The reason why the game cannot start is that lithium excludes `1.21` in the version requirement part inside the `fabric.mod.json`

As a workaround, you can follow the steps below to bypass lithium's version check:

1. Download a lithium.jar for mc1.21.1 (e.g. `lithium-fabric-0.14.2-snapshot+mc1.21.1-build.90.jar`)
2. Edit the `fabric.mod.json` file inside the jar
3. Replace the version requirement string `"minecraft" : "1.21.1"` with `"minecraft" : "1.21"`, or even `"minecraft" : "1.21.x"`
4. Done

**Comment by jcw780** [comment]
FYI as of Lithium 1.21.1 0.15.2, the latest 1.21.1 version is also compatible with 1.21 without requiring overrides / modifications. 
As such, this is no longer an issue.
