### ISSUE TITLE
关于声音抑制防崩服

### ISSUE THREAD

**Issue by RedstoneRepeater** [TISUnion/Carpet-TIS-Addition#187]
### Motivation

希望使用声音抑制器换底，但是carpet TIS addition等的更新抑制防崩仅支持栈溢出，oom与cce，如果能够避免IAE异常的崩服就可以解决声音抑制的不稳定问题

### Description

希望更新抑制防崩服功能支持IAE异常导致的崩服

**Comment by Fallen-Breath** [comment]
与 #169 重复

**Comment by RedstoneRepeater** [comment]
但是在1.19到1.21的版本均保留有声音抑制，这些版本能否添加防崩功能？以及是否可以将1.21.1以上修复方块实体不一致的功能迁移到低版本？

**Comment by RedstoneRepeater** [comment]
但是在1.19到1.21的版本均保留有声音抑制，这些版本能否添加防崩功能？以及是否可以将1.21.1以上修复方块实体不一致的功能迁移到低版本？

**Comment by Fallen-Breath** [comment]
> 但是在1.19到1.21的版本均保留有声音抑制，这些版本能否添加防崩功能？以及是否可以将1.21.1以上修复方块实体不一致的功能迁移到低版本？

所提问题均与 #169 重复
