### ISSUE TITLE
Incompatible with Fabric-Rug

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [TISUnion/Carpet-TIS-Addition#19]
Crash on startup with [Fabric-Rug](https://github.com/RubixDev) (another fabric extension mod). Here is the log (no crash report):
https://gist.github.com/DragonEggBedrockBreaking/df2698ceb045713425205cfc8d7314be

**Comment by DragonEggBedrockBreaking** [comment]
Update: The person who coded Fabric-Rug said that he managed to get it to work, so I will close this when it is pushed to GitHub and a release is published.

**Comment by RubixDev** [comment]
It's fixed on my side now ;)
