### ISSUE TITLE
[QUESTION] Renewable Dragon Egg

### ISSUE THREAD

**Issue by srnyx** [TISUnion/Carpet-TIS-Addition#20]
How do I do it?

**Comment by Fallen-Breath** [comment]
Read the readme or rule descipbtion in game plz
https://github.com/TISUnion/Carpet-TIS-Addition#renewableDragonEgg

**Comment by srnyx** [comment]
> Read the readme or rule descipbtion in game plz
> https://github.com/TISUnion/Carpet-TIS-Addition#renewableDragonEgg

I did, it doesn't help.
Do you drop it in, place it, does the cloud need to be on the ground?

**Comment by Fallen-Breath** [comment]
If you read it have u tried `dragon egg in dragon breath effect cloud` urself in game first? The description is clean enough, i doubt if there's any other way of understanding

**Comment by srnyx** [comment]
> If you read it have u tried `dragon egg in dragon breath effect cloud` urself in game first? The description is clean enough, i doubt if there's any other way of understanding

Yes, but either it's not working or I'm doing it wrong.
Can you still answer my question? Do you **drop (Q)** the dragon egg or do you **place (right-click)** the dragon egg in the cloud?

**Comment by Fallen-Breath** [comment]
> Do you **drop (Q)** the dragon egg or do you **place (right-click)** the dragon egg in the cloud?

place (right-click) the dragon egg
