### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by srnyx** [TISUnion/Carpet-TIS-Addition#25]
Whenever someone tries to join, they are immediately kicked from the server.
This is because Carpet TIS Addition isn't compatible with the latest version of Carpet (v1.4.34).

Here are the errors/warnings that were sent in the console when someone tried to join: https://paste.srnyx.xyz/emabuvikaq.sql

Reverting to a previous version of Carpet (v1.4.33) allows it to work again.

**Comment by Fallen-Breath** [comment]
Ah the signature of method `carpet.script.utils.ShapeDispatcher#sendShape` got changed in 1.4.33 with commit https://github.com/gnembon/fabric-carpet/commit/28101e716b0f0bc948ec6f2c060425d619f83f10, which causes this exception

Time for v1.17.1 and also fabric carpet version requirement update

**Comment by Fallen-Breath** [comment]
https://github.com/TISUnion/Carpet-TIS-Addition/actions/runs/804137871

try this

**Comment by srnyx** [comment]
> try this

https://paste.srnyx.xyz/tuhacisata.pl

**Comment by Fallen-Breath** [comment]
> > try this
> 
> https://paste.srnyx.xyz/tuhacisata.pl

This doesnt seem to be related to carpet-tis-addition

**Comment by srnyx** [comment]
> This doesnt seem to be related to carpet-tis-addition

What is it related to then?

**Comment by Fallen-Breath** [comment]
> > > > try this
> > > 
> > > 
> > > [paste.srnyx.xyz/tuhacisata.pl](https://paste.srnyx.xyz/tuhacisata.pl)
> > 
> > 
> > This doesnt seem to be related to carpet-tis-addition
> 
> What is it related to then? ~Cause it only happens when using Carpet v1.v.34 and Carpet TIS Addition v1.17.1 (the one you sent me).~

Gunpowder

**Comment by srnyx** [comment]
> Gunpowder

Ok, I fixed Gunpowder.


> [TISUnion/Carpet-TIS-Addition/actions/runs/804137871](https://github.com/TISUnion/Carpet-TIS-Addition/actions/runs/804137871)
> 
> try this

Works, thanks!

**Comment by Fallen-Breath** [comment]
Just released the build https://github.com/TISUnion/Carpet-TIS-Addition/releases/tag/v1.17.1
