### ISSUE TITLE
[suggestions]

### ISSUE THREAD

**Issue by T-727** [TISUnion/Carpet-TIS-Addition#26]
- adding /log tickwarp to defaultLoggers
- adding /carpet hopperNoItemCost
(hopper with wool on top keeps pushing the item from the first slot infinitely)

**Comment by Fallen-Breath** [comment]
> adding /log tickwarp to defaultLoggers

imo it's not a widely used thing, and it requires to ~~hack~~ mixin into fabric-carpet

> adding /carpet hopperNoItemCost

that's a good idea, hopefully it can be implemented elegantly

**Comment by Fallen-Breath** [comment]
See [v1.18](https://github.com/TISUnion/Carpet-TIS-Addition/releases/tag/v1.18.0), there goes ur `hopperNoItemCost`
