### ISSUE TITLE
[Suggestion] Allow unusual characters in fakePlayer prefix and suffix

### ISSUE THREAD

**Issue by Metacinnabar** [TISUnion/Carpet-TIS-Addition#28]
To actually have special bot names, because with the prefixes and suffixes currently allowed, they can still be possibly registered names. I know this is possible because Geyser does it with bedrock players

**Comment by Fallen-Breath** [comment]
I'm afraid that unusual character names might cause unintended behaviors in some aspects or with other mods

**Comment by Metacinnabar** [comment]
I guess a warning text could be presented to the admin?
