### ISSUE TITLE
Console error 

### ISSUE THREAD

**Issue by srnyx** [TISUnion/Carpet-TIS-Addition#29]
https://paste.srnyx.xyz/zecosafogu.properties

Fabric 1.16.5 Java 16

**Comment by Fallen-Breath** [comment]
Any method to reproduce it?

**Comment by Fallen-Breath** [comment]
Might be related to some other mods, gonna fix that whatever, but still the minumum conditions to reproduce it is helpful

**Comment by srnyx** [comment]
> Might be related to some other mods, gonna fix that whatever, but still the minumum conditions to reproduce it is helpful

It just occurs on startup

**Comment by Fallen-Breath** [comment]
Try removing some mods and find the minimum mod list to reproduce it. It doens't happen in vanilla
