### ISSUE TITLE
[suggestion] restore 1.16 behaviour of stacked shulker boxes in inventories

### ISSUE THREAD

**Issue by nogutsnoglory69** [TISUnion/Carpet-TIS-Addition#31]
I've noticed since updating to 1.17 that you can no longer move stacked shulker boxes around inventories without them unstacking unless you're shift clicking. This is kind of annoying. Would be cool if you could add pre 1.17 behaviour as an optional feature.

**Comment by Fallen-Breath** [comment]
Stackable shulker box thing is a fabric-carpet feature, so I'll suggest you to make a suggestion there

**Comment by nogutsnoglory69** [comment]
Fair, I'll go ahead and suggest that there. No clue why I didn't think of that myself.
