### ISSUE TITLE
Completely moving EntityInfo code into Carpet TIS

### ISSUE THREAD

**Issue by altrisi** [TISUnion/Carpet-TIS-Addition#32]
Sorry. It's me breaking the extension again.

gnembon/fabric-carpet#1033.

Basically since it uses code in Carpet that isn't used anywhere else so it'll likely be removed when it gets removed, and will probably crash with the next Carpet version without it else.

I'll probably make the PR that removes it from Carpet in the near future, maybe today, I'll link the PR in this issue then. It's just an annoying remnant in servers without Carpet TIS.

**Comment by Fallen-Breath** [comment]
Ah xd that's fine. Every mixin into fabric carpet is expected to be broken when carpet makes some changes

For the reason why I ported `/info entity`, I just wrote them in the related fabric carpet issue comment https://github.com/gnembon/fabric-carpet/issues/1033#issuecomment-893473696

**Comment by altrisi** [comment]
The PR is gnembon/fabric-carpet#1047, specifically commit [`c977f17` (gnembon/fabric-carpet#1047)](https://github.com/gnembon/fabric-carpet/pull/1047/commits/c977f17e4d1b7aa4d187b3aebe10c5c09c961b2c).

Should be all about porting the `EntityInfo` class instead of using the accessor, port the two methods from the command class and mix in to send the whole `entities` subcommand tree to brigadier instead of changing the `EntityInfo` method to use the ported method.
