### ISSUE TITLE
Liquids ignoring totallyNoBlockUpdate

### ISSUE THREAD

**Issue by Krebs-Cycle** [TISUnion/Carpet-TIS-Addition#33]
Carpet version: 1.4.44
Carpet TIS Addition version: 1.21.0 build 641
1.16.5

When water or lava is placed, it begins to flow as normal even when totallyNoBlockUpdate is set to true. This also occurs when a waterlogged block is broken even though placing the block in the water source does not update it and cause it to begin flowing.

Here's an example of what breaking a waterlogged block does. If you place the slab in the water source, the source block will not spread out, but water will flow down and flow as normal. If you do it again, then the source block will spread out.
![2021-08-19_12 21 12](https://user-images.githubusercontent.com/6492475/130114709-0b0315bb-cf56-4db2-bd34-713cb44da9e0.png)

**Comment by Fallen-Breath** [comment]
Rule `totallyNoBlockUpdate` only removes any kinds of block updates. It doesn't prevent schedule ticks or block events from executing. The shown liquid logic doesn't invoke block updates, it's just some liquid tiletick things
