### ISSUE TITLE
opPlayerNoCheat missing commands

### ISSUE THREAD

**Issue by CodeF53** [TISUnion/Carpet-TIS-Addition#36]
There are several commands that the rule opPlayerNoCheat misses.

Here are the ones I have found so far:
`/fill` - should be disabled for the same reason `/setblock` is

`/enchant` - allows enchanting tools without xp/books

`/experience` and `/xp` allows giving self or others xp.

**Comment by CodeF53** [comment]
`/advancement`

**Comment by CodeF53** [comment]
`/effect` - give saturation to self / instantly kill others
`/defaultgamemode` - can really cause issues
`/kill`
`/data` - /data modify block 542 66 903 Items[0].id set value "minecraft:diamond_block"

**Comment by Fallen-Breath** [comment]
Rule `opNoCheat` is not designed for disabling all possible cheaty commands, but for disabling commands that are cheaty and can be unintended triggered

e.g.

- `/gamemode`: via F3+N
- `/teleport`: via clicking in minimap mods

I won't add commands that don't have unintended triggering cases

**Comment by Fallen-Breath** [comment]
Since you already have op permission, if you do want to cheat, you can just disable this rule with `/carpet opPlayerNoCheat false`
