### ISSUE TITLE
Incompatible with Lithium 0.7.4

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [TISUnion/Carpet-TIS-Addition#37]
Lithium 0.7.4 was just released and this mod is incompatible (crash on startup). Log: https://gist.github.com/DragonEggBedrockBreaking/089ada6b539cba5363323e7f9f3c903e

There is a workaround (by disabling a lithium mixin). You need to put `mixin.world.tick_scheduler=false` into `.minecraft/config/lithium.properties`. This can also be done in carpet-tis-additions if no other solution is found (this does NOT make Lithium a dependency, so it can be put in without worrying about that) - put the following into `src/main/resources/fabric.mod.json`:
```json
"custom": {
    "lithium:options": {
        "mixin.world.tick_scheduler": false
    }
}
```

**Comment by Fallen-Breath** [comment]
Fixed in v1.21.1 (1.17.x only)
