### ISSUE TITLE
Keep mobs in lazy chunk rule is obsolete in 1.17

### ISSUE THREAD

**Issue by nogutsnoglory69** [TISUnion/Carpet-TIS-Addition#39]
Apparently mobs do not despawn in lazy chunks anymore in 1.17, so that rule could be removed as it does nothing.

**Comment by Fallen-Breath** [comment]
I will choose to keep this rule, but give a hint about this rule doing nothing in the description.

Since mob despawns in lazy chunks are mojang's intended change (https://bugs.mojang.com/browse/MC-155289), maybe mojang will somehow bring this back again in the future
