### ISSUE TITLE
Feature Suggestion: only non hostile mobs don't despawn in lazy chunks

### ISSUE THREAD

**Issue by nogutsnoglory69** [TISUnion/Carpet-TIS-Addition#4]
Hey, could you add a variation of mobs don't despawn in lazy chunks that allows hostile mobs to despawn but no other types of mobs? I quite like that hostile mobs despawn in lazy chunks, so turning on that feature right now would be a bummer for me.

**Comment by DragonEggBedrockBreaking** [comment]
But that's vanilla - passive mobs already don't despawn at all. Pls close issue.

**Comment by Fallen-Breath** [comment]
> But that's vanilla - passive mobs already don't despawn at all. Pls close issue.

But Ambient and WaterCreature mobs do despawn. tho I'm not planning to add this rule since it's not that a general rule

**Comment by DragonEggBedrockBreaking** [comment]
@nogutsnoglory69 
If @Fallen-Breath is not goint to add this, pls can you close this.
