### ISSUE TITLE
tick warp status crashes server

### ISSUE THREAD

**Issue by Assaro** [TISUnion/Carpet-TIS-Addition#44]
Using /tick warp status crashes my server on 1.18.
Crash logs show TIS-Addition
logs and modlist are attached
[crash-2021-12-01_09.10.06-server.txt](https://github.com/TISUnion/Carpet-TIS-Addition/files/7631996/crash-2021-12-01_09.10.06-server.txt)

![image](https://user-images.githubusercontent.com/13085620/144196458-afadad11-8a6c-4c05-9b7c-7c2907617af1.png)

**Comment by Fallen-Breath** [comment]
seems to be some merging issue, applying quick fix

**Comment by Fallen-Breath** [comment]
Updated release assets, go check v1.26.1 for 1.18

**Comment by Assaro** [comment]
Quick tests seems to be working. Will test it extensively in my free time
