### ISSUE TITLE
/player <玩家名稱> spawn 在 1.18 出現未預期的錯誤

### ISSUE THREAD

**Issue by whes1015** [TISUnion/Carpet-TIS-Addition#45]

**Comment by Fallen-Breath** [comment]
请提供必要的信息，包括游戏版本、mod列表、游戏日志、复现方式等，并检查在移除本 mod 后是否还有相同错误发生

**Comment by whes1015** [comment]
> 请提供必要的信息，包括游戏版本、mod列表、游戏日志、复现方式等，并检查在移除本 mod 后是否还有相同错误发生

測試過了，這個問題應該跟 TIS addition 無關，應該是 carpet 的問題

**Comment by whes1015** [comment]
![IMG_20211207_142214](https://user-images.githubusercontent.com/44525760/144977237-c4f2b586-1e3d-4d72-8c8b-b5cbb49686fe.jpg)
