### ISSUE TITLE
大木桶功能，某些行为与大箱子不太一致。

### ISSUE THREAD

**Issue by Next-Page-Vi** [TISUnion/Carpet-TIS-Addition#49]
![image](https://user-images.githubusercontent.com/52558763/147460943-b8a5b6a0-423b-4ad5-8f51-0c7b3effa8f1.png)
![image](https://user-images.githubusercontent.com/52558763/147460966-884471f9-44c6-41e2-bcbb-d6e34a6acfb4.png)
![image](https://user-images.githubusercontent.com/52558763/147460972-3e45baf2-1ca2-49d6-be47-663b82c202da.png)
如图，漏斗不能向相邻的小木桶传输物品。

**Comment by Fallen-Breath** [comment]
请给出 mod 列表、游戏版本。如果有 lithium mod 的话可以尝试将其删去（猜测）

**Comment by Next-Page-Vi** [comment]
删掉 lithium 后问题解决了，感谢佛冷快速回答，很难想到与 lithium 有关。

**Comment by Fallen-Breath** [comment]
不过不需要关掉这个 issue，毕竟这也属于 mod 兼容性的范畴

**Comment by Fallen-Breath** [comment]
可以试试这两个对于 1.17 跟 1.18 的版本，看看能不能跟锂和谐共处

- 1.17 https://github.com/TISUnion/Carpet-TIS-Addition/actions/runs/1627242637
- 1.18 https://github.com/TISUnion/Carpet-TIS-Addition/actions/runs/1627243518

**Comment by Fallen-Breath** [comment]
已于 v1.28.0 修复
