### ISSUE TITLE
Villagers Visually Missing

### ISSUE THREAD

**Issue by Jh16** [TISUnion/Carpet-TIS-Addition#50]
With v1.28.0 for some reason my villagers are visually missing, I can hear them but can't see them.
Noticed them missing when I went to go trade but didn't see them and I disabled the three mods I had updated recently. Narrowed it down to this one causing them to be visually not there.

Let me know if you need anything else.

**Comment by Fallen-Breath** [comment]
please send mod list, minecraft version, and steps to reproduce what u saw

**Comment by Jh16** [comment]
Mod List:
> carpet-tis-addition-mc1.18.1-v1.28.0.jar
> fabric-api-0.45.0+1.18.jar
> fabric-carpet-1.18-1.4.56+v211130.jar

MC 1.18.1
Fabric Loader v0.12.12

Create new world or join an existing one, give villager egg and use it or go visit a location you know that has villagers. You will be able to hear the villager but not visually see it.

**Comment by Redlnn** [comment]
My game also has this problem. See [this link](https://pastebin.com/z5r4N4Rf) for the log

**Comment by Fallen-Breath** [comment]
Fixed in v1.28.1
