### ISSUE TITLE
Error in parsing dimension in suggested tp command

### ISSUE THREAD

**Issue by CommandLeo** [TISUnion/Carpet-TIS-Addition#51]
**Description**
Dimension isn't parsed correctly when a tp command is suggested by a logger.
Related code: https://github.com/TISUnion/Carpet-TIS-Addition/blob/96094ef2be6ff6d5361c8b3881648e24b983c76a/src/main/java/carpettisaddition/utils/Messenger.java#L138-L146

**Steps to reproduce**
- Turn on item (creation) logging with `/log item create`
- Drop an item
- Click on the coordinates
![image](https://user-images.githubusercontent.com/51045936/147610004-89b5ea80-6d43-4915-88d7-b344c747509f.png)
A command should pop up in chat

**Expected Result**
The suggested command looks like this: `/execute in minecraft:overworld run tp 176.0698523481682 16.602718537233475 714.2538320022973`

**Actual Result**
The dimension is parsed incorrectly and the command looks like this: `/execute in ResourceKey[minecraft:dimension / minecraft:overworld] run tp 176.0698523481682 16.602718537233475 714.2538320022973`

**Comment by Fallen-Breath** [comment]
What's your mod version? This issue should already be fixed in v1.27.3 and above
