### ISSUE TITLE
Request survival use of the autoclicker and player spawning 

### ISSUE THREAD

**Issue by AmLaggen** [TISUnion/Carpet-TIS-Addition#53]
be able to activate the /player command without cheats (of course with a on and of switch )

**Comment by Fallen-Breath** [comment]
It would be better to suggest this in fabric carpet repository, since player command is a carpet core's funtionality, just like the /tick and /profile command thing

**Comment by AmLaggen** [comment]
Thx there is already a way with the /carpet commandplayer command
