### ISSUE TITLE
tis addition with rug crash the game

### ISSUE THREAD

**Issue by Pietr06** [TISUnion/Carpet-TIS-Addition#54]
Carpet TIS addition with RubixDev's rug mod crash the game

**Comment by DragonEggBedrockBreaking** [comment]
Crash report?

**Comment by Pietr06** [comment]
true lol 
just a moment

**Comment by Pi3tro88** [comment]
no, sorry im wrong  the issue its with another mod, i should create a new issue or edit this one?

**Comment by Pietr06** [comment]
nevermind sorry, i was wrong now it works idk why
