### ISSUE TITLE
大木桶是否应该被活塞一起推动

### ISSUE THREAD

**Issue by plusls** [TISUnion/Carpet-TIS-Addition#56]
在开了 carpet 的可移动方块实体后，大箱子会作为一个整体被活塞推动，是否考虑让大木桶能被一起推动呢

**Comment by Fallen-Breath** [comment]
对于推容方面的应用，如果让大木桶作为一个整体运动的话，是无法做到将大木桶拆成两个小木桶的，因为木桶不像箱子一样自带着可用于记录单箱/双箱的方块状态，玩家无法通过木桶初始状态使电路区分出是要把这些木桶看做一个整体，还是多个小木桶。因此，如果把大木桶看做一个整体，玩家就失去了拆分木桶分别移动的能力，反而会使趣味性下降

因此大木桶无法被作为整体推动是刻意的行为
