### ISSUE TITLE
starlight mod is not compatible with Carpet-TIS-Addition mod's command "/log lightQueue"

### ISSUE THREAD

**Issue by haha44444** [TISUnion/Carpet-TIS-Addition#57]
Carpet-TIS-Addition's command "/log lightQueue" doesn't work when I add starlight mod to server. The values will all become 0 and will not change. Starlight mod completely rewrites minecraft's terrible lighting engine. Maybe this is the problem, can it be fixed, because the starlight mod is a big boost to my server. you know, in 1.18, the optimizations brought by the phosphor mod are not enough. thx.

you can find the starlight mod in here: https://github.com/PaperMC/Starlight

reply的话直接用中文就好啦
(其实是刚才搞错了把issue发到fabric-carpet那里去了，然后直接copy过来懒得再写一遍了 XD

**Comment by Fallen-Breath** [comment]
Works as intended. Startlight 重写了光照引擎，本 mod 的相关功能也就无法运作了。~~至少没崩~~

**Comment by haha44444** [comment]
这东西真的没法解决了嘛呜呜，看着难受（真的），可不可以这样，就是先判断是否使用了starlight mod，然后用starlight的算法重新计算光照（毕竟starlight这东西是open source的）

**Comment by Fallen-Breath** [comment]
可以但没必要，因为既然都已经装了 startlight 了，那就完全不需要考虑光照抑制相关的游戏机制了，因此 lightQueue logger 相关的功能也是完全没必要的了

**Comment by haha44444** [comment]
ok, i know. 所以就是说装了starlight后，光照更新抑制器几乎无法工作？（因为光照计算的太快了？）

**Comment by Fallen-Breath** [comment]
是的

**Comment by haha44444** [comment]
嘶，但1.18那东西真就性能堪忧 :(
就这样好了，close吧，目前除了开启 [光照与主线程同步] +把 [光照引擎任务组数] 调大之外应该没有更好的办法了
因为光照更新抑制器那东西在某些地方还是得用的

**Comment by Slashtaker** [comment]
这个carpet tis addition有什么办法可以装在伺服器上吗？
