### ISSUE TITLE
Crash with Carpet v1.4.19

### ISSUE THREAD

**Issue by Spacebarium** [TISUnion/Carpet-TIS-Addition#6]
using carpet-tis v1.9.1
crash log: [crash-2020-11-27_19.18.51-server.txt](https://github.com/TISUnion/Carpet-TIS-Addition/files/5607644/crash-2020-11-27_19.18.51-server.txt) or https://paste.ee/p/VVUPu

crashes upon joining a world. however, it doesn't crash with carpet v1.4.18

**Comment by Fallen-Breath** [comment]
fabric-carpet v1.4.19 changed the signature of method `canUseCommand` which causes the crash

**Comment by Fallen-Breath** [comment]
fixed in 1.9.2, check the release page

**Comment by lucy** [comment]
1.9.2 works with latest carpet for me
