### ISSUE TITLE
在log explosions full时红石触发tnt会导致游戏抛出异常

### ISSUE THREAD

**Issue by Snow-dash** [TISUnion/Carpet-TIS-Addition#61]
复现：
进入游戏，输入/log explosions full，放置tnt在空气中，在旁边放置红石块，tnt到达爆炸时间后游戏崩溃。

环境：
minecraft 1.18.1
fabric loader 0.12.12
fabric-api-0.46.4+1.18
fabric-carpet-1.18.1-1.4.57+v220119
carpet-tis-addition-mc1.18.1-v1.30.0

只有carpet本体时没有这个bug，加上tis addtiton才能触发。

日志：[minecraft.log](https://github.com/TISUnion/Carpet-TIS-Addition/files/8480796/minecraft.log)

**Comment by Fallen-Breath** [comment]
已于 v1.32.2 中修复

由于 mc1.18.1 已不再维护，如果你仍需要使用 1.18.1 的话可以用 https://github.com/TISUnion/Carpet-TIS-Addition/actions/runs/2160917861 中的的构建，即 [build-artifacts - 2022-04-13T194328.534.zip](https://github.com/TISUnion/Carpet-TIS-Addition/files/8481129/build-artifacts.-.2022-04-13T194328.534.zip)

**Comment by Snow-dash** [comment]
> 已于 v1.32.2 中修复
> 
> 由于 mc1.18.1 已不再维护，如果你仍需要使用 1.18.1 的话可以用 https://github.com/TISUnion/Carpet-TIS-Addition/actions/runs/2160917861 中的的构建，即 [build-artifacts - 2022-04-13T194328.534.zip](https://github.com/TISUnion/Carpet-TIS-Addition/files/8481129/build-artifacts.-.2022-04-13T194328.534.zip)

好些mod这次跟进1.18.2有些慢。。
