### ISSUE TITLE
default_carpet.conf?

### ISSUE THREAD

**Issue by Nekkok** [TISUnion/Carpet-TIS-Addition#63]
Sorry to ask this, but the new options added by this mod save in the default_carpet.conf in trhe config/carpet folder? They don't seem to work for me... Thank you.

**Comment by Fallen-Breath** [comment]
What do you want to ask? What do you mean "don't seem to work"

**Comment by Fallen-Breath** [comment]
Please describe: What you did, What you expected to see but instead what happened

**Comment by Nekkok** [comment]
I saved my settings on said default_carpet.conf file, like "largeBarrel true" but whenever I start a world this options doesn't work, hoping it would so. Is it possible to permanent save settings or do I have to enable them on every world? Sorry, I'm new to the carpet suite.

**Comment by Fallen-Breath** [comment]
It works for me tho

Steps:

1. having line `largeBarrel true` in `.minecraft/config/default_carpet.conf`
2. create a new world
3. \>\> Rule `largeBarrel` is set to true

With:

- MC 1.18.2
- fabric-carpet-1.18.2-1.4.66 v220228
- carpet-tis-addition-mc1.18.2-v1.36.0

**Comment by Nekkok** [comment]
Sorry for the late reply. I just saw that another related issue about the "BigBarrel" rule which, correct me if I'm wrong, is the same largeBarrel rule. I also have lithium installed so then that would explain why is not working for me and this issue could be closed. Thank you again.

**Comment by Fallen-Breath** [comment]
This issue doesn't seem to be related to that lithium compatibility issue
