### ISSUE TITLE
BigBarrel is incompatible with Lithium 0.8

### ISSUE THREAD

**Issue by QPCrummer** [TISUnion/Carpet-TIS-Addition#64]
https://pastebin.com/PkE8DYE8

**Comment by Fallen-Breath** [comment]
Lithium 0.8 is not released and I won't fix that until it's released

**Comment by 2No2Name** [comment]
Lithium 0.8.0 is released. The API provided by the hopper optimizations to notify about changing transfer conditions changed slightly.

**Comment by Fallen-Breath** [comment]
Fixed in v1.36.1
