### ISSUE TITLE
Mixin apply failure 1.19.1

### ISSUE THREAD

**Issue by QPCrummer** [TISUnion/Carpet-TIS-Addition#75]
https://mclo.gs/rBmxvzv
Fabric 0.14.8

**Comment by Fallen-Breath** [comment]
mc 1.19.1 version is not released yet, but u can try the dev version in github actions, e.g. Trying for them not to be anymore :

**Comment by QPCrummer** [comment]
That should be the github actions dev branch that I was using

**Comment by Fallen-Breath** [comment]
> That should be the github actions dev branch that I was using

are you sure you are using the jars in the `future` folder? cuz i haven't migrate the `1.19` subproject to `1.19.1` yet and the 1.19.1 stuffs are in `future`

**Comment by QPCrummer** [comment]
oh lol, I was using 1.19.x. Sorry for this issue then
