### ISSUE TITLE
Aug 2nd update makes no sense

### ISSUE THREAD

**Issue by itsdinkd** [TISUnion/Carpet-TIS-Addition#76]
For 1.18.2 it says on the update fixed lithium crash 8.0+, however 8,0+ is 1.19. 

Lithium is on 7.10 for 1.18.2, so is there going to be conflictions?

**Comment by Fallen-Breath** [comment]
[Lithium 0.8.1](https://github.com/CaffeineMC/lithium-fabric/releases/tag/mc1.18.2-0.8.1) does exist for mc 1.18.2.

**Comment by itsdinkd** [comment]
> [Lithium 0.8.1](https://github.com/CaffeineMC/lithium-fabric/releases/tag/mc1.18.2-0.8.1) does exist for mc 1.18.2.

This is not on curseforge, meaning I cannot add it to my modpack and put that modpack on curseforge.

![image](https://user-images.githubusercontent.com/35115304/183714218-1e8feb99-bf70-4e3a-b0cc-c48cf983dc18.png)

**Comment by Fallen-Breath** [comment]
Then go complain lithium mod about that

**Comment by itsdinkd** [comment]
> Then go complain lithium mod about that

I'm not here to complain? But seeing how you think what's I'm doing, I'll just remove your mod from my modpack. Enjoy the less credits. Imagine losing the only modpack that added your mod giving 350k downloads. Oof.

**Comment by Fallen-Breath** [comment]
I don't care. Go do what you want to do.
