### ISSUE TITLE
create 机械动力的溜槽不能与 largeBarrel 大木桶功能正常工作。

### ISSUE THREAD

**Issue by Next-Page-Vi** [TISUnion/Carpet-TIS-Addition#77]
<img width="1280" alt="1" src="https://user-images.githubusercontent.com/52558763/183705330-aae2e0c7-b573-4bcc-8406-ae538d41a316.png">
<img width="1280" alt="2" src="https://user-images.githubusercontent.com/52558763/183705338-bc52fbe3-c2f2-4d31-a1f6-ce4ce4c49462.png">
如上图，开启大木桶功能后，溜槽不能正常的向连接的另一个木桶输送物品，但是原版的漏斗是可以正常工作的。

Minecraft Version: 1.18.2
carpet-tis-addition: Carpet TIS Addition 1.39.0
create: Create 0.5.0c-708
carpet: Carpet Mod 1.4.69
lithium: Lithium 0.8.1

**Comment by Fallen-Breath** [comment]
看了下 create 的代码，它是用了 fabric api 的 `fabric-transfer-api-v1` 来实现漏斗交互逻辑的，这是值得去兼容的

**Comment by Fallen-Breath** [comment]
你可以试试这里的构建，看看是否解决了问题：

已于以下的环境中测试：https://github.com/TISUnion/Carpet-TIS-Addition/actions/runs/2899229675

- mc: 1.18.2
- fabric carpet: 1.4.66
- fabric api: 0.58.0+1.18.2
- create: Create 0.5.0c-708

**Comment by Next-Page-Vi** [comment]
![image](https://user-images.githubusercontent.com/52558763/185821761-414b95e3-611b-43b2-98ee-28383bb34ec2.png)
在服务器环境中测试，目前溜槽可以向相邻的木桶方块输送物品了。
