### ISSUE TITLE
关于opPlayerNoCheat功能的建议

### ISSUE THREAD

**Issue by Ryuz1nc** [TISUnion/Carpet-TIS-Addition#78]
## Motivation
mod版本:carpet-tis-addition-mc1.19.1-v1.39.0.jar
我在游戏内将op玩家不准作弊（opPlayerNoCheat)打开时发现/enchant，/effect，/fill，/xp指令依然可以使用

## Description 

在opPlayerNoCheat为true时禁用/enchant，/effect，/fill，/xp

**Comment by Fallen-Breath** [comment]
请仔细阅读规则描述 / 相关文档，了解规则 `opPlayerNoCheat` 的设计意图。此规则不是用于阻止作弊的，而是用于防止**误触导致的**作弊的

与 #36 重复
