### ISSUE TITLE
跟锂一起装崩溃，无法启动

### ISSUE THREAD

**Issue by yyx0193** [TISUnion/Carpet-TIS-Addition#79]
## Description

把锂更新到0.7.10，TIS addition从1.18.2 v1.38.0更新到1.39.0后，启动游戏提示跟Lithium 0.7.10不兼容，把锂换成0.7.9也不行，用1.38.0可以跟锂0.7.10启动。

![屏幕截图 2022-08-29 113557](https://user-images.githubusercontent.com/110516955/187119205-791300fd-cf75-4d19-84ce-6f2f098faf25.png)

## To Reproduce

4. ...

What you expect to see: '...'

What actually happens: '...'

## Environment

Describe the environment to reproduce this bug:

- Minecraft version: '1.18.2'
- Fabric Carpet version: '1.18.2-1.4.69+v220331'
- Carpet TIS Addition version: '1.18.2-v1.39.0'
- Other related mod versions: 'lithium-fabric-mc1.18.2-0.7.9'
- ...

## Log

[latest.log](https://github.com/TISUnion/Carpet-TIS-Addition/files/9441478/latest.log)

**Comment by Fallen-Breath** [comment]
正如你启动游戏时显示的文本所述，你需要一个版本更新的 lithium 模组。请更新你的 lithium 模组到 0.8.0 及以上

**Comment by yyx0193** [comment]
1.18.2的锂最新版只到0.7.10，那就是说只能用v1.38.0了吧。

**Comment by Fallen-Breath** [comment]
1.18.2 有 0.8.0 以上版本的锂，如 https://github.com/CaffeineMC/lithium-fabric/releases/tag/mc1.18.2-0.8.1

**Comment by yyx0193** [comment]
不好意思qaq，之前在modrinth和courseforge上没找到，谢谢狐狸。还有，大木桶真好用！
