### ISSUE TITLE
Mod does not appear in ModMenu

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [TISUnion/Carpet-TIS-Addition#8]
Mod does not appear in ModMenu, even though all my other mods do. Even when I show libraries (e.g. Fabric API) it still doesn't show up. It works perfectly and all the features work, so it is definitely in the game and working, but it just does not appear in ModMenu.

**Comment by Fallen-Breath** [comment]
It should be inside the modmenu. it's a sub-mod of fabric-carpet, go look around the fabric carpet entry

**Comment by DragonEggBedrockBreaking** [comment]
Ah, I found it here:

![image](https://user-images.githubusercontent.com/68545280/102013827-7c774e80-3d4a-11eb-8203-628f36d18cde.png)

Why is it like this? None of the other carpet extension mods are like this...

![image](https://user-images.githubusercontent.com/68545280/102013858-a2045800-3d4a-11eb-872e-c066cf21afa5.png)

**Comment by Fallen-Breath** [comment]
nah i can't disturb other extensions, but i can at least mark mine as a sub-mod of fabric-carpet to make it look nicer
