### ISSUE TITLE
Double barrel incompatible with Lithium 0.9.0

### ISSUE THREAD

**Issue by 2No2Name** [TISUnion/Carpet-TIS-Addition#80]
## Description

Lithium changed its API, so the double barrel thing broke again. :(
## To Reproduce

1. Install Lithium 0.9.0 and carpet-tis-addition
2. Try to place double barrel and a hopper interacting with it
3. I think it crashes before finishing step 2.

## Environment

Describe the environment to reproduce this bug:

- Minecraft version: '1.19.2'
- Lithium: '0.9.0'
- Fabric Carpet version: unknown
- Carpet TIS Addition version: unknown
- Other related mod versions: unknown

## Log
Crash log here
https://github.com/CaffeineMC/lithium-fabric/issues/397

**Comment by Fallen-Breath** [comment]
Fixed by assuming `me.jellysquid.mods.lithium.common.hopper.RemovalCounter#increaseRemovedCounter` is changed to `me.jellysquid.mods.lithium.common.block.entity.inventory_change_tracking.InventoryChangeEmitter#emitRemoved` and that's all I need to adjust
