### ISSUE TITLE
hopperCountersUnlimitedSpeed incompatable with Lithium 0.9.1 

### ISSUE THREAD

**Issue by Hnaguski** [TISUnion/Carpet-TIS-Addition#81]
## Description

Having both Lithium 0.9.1 installed, and the `hopperCountersUnlimitedSpeed` rule enabled causes the game to crash when an item is thrown into a hopper counter

## To Reproduce

1. Install Carpet-TIS-Addition 1.40.1 and Lithium 0.9.1
2. Open a world, enable `hopperCounters` and `hopperCountersUnlimitedSpeed`
3. Place a hopper pointing into wool
4. Throw item into hopper

What you expect to see: The game doesn't crash, and an item is counted

What actually happens: The game crashes

## Environment

Describe the environment to reproduce this bug:

- Minecraft version: '1.19.2'
- Fabric Carpet version: '1.4.83'
- Carpet TIS Addition version: '1.40.1'
- Lithium version: '0.9.1'

## Log
[crash-2022-10-14_16.47.41-server.txt](https://github.com/TISUnion/Carpet-TIS-Addition/files/9790624/crash-2022-10-14_16.47.41-server.txt)

**Comment by Fallen-Breath** [comment]
Oh no lithium is setting some variable to null, idk why they do that

**Comment by Hnaguski** [comment]
Hmm, might be worth making an issue on lithium's tracker, or at least ask 2no in the discord. If it'd be helpful, I can do either

**Comment by Fallen-Breath** [comment]
> Hmm, might be worth making an issue on lithium's tracker, or at least ask 2no in the discord

ye I have asked in CaffeineMC discord's `#dev-lithium`

**Comment by Fallen-Breath** [comment]
Waiting lithium to fix that on their side (probably in lithium 0.9.2)

**Comment by Hnaguski** [comment]
This appears to have been fixed with Lithium 0.10.0
