### ISSUE TITLE
Question about: creativeNetherWaterPlacement

### ISSUE THREAD

**Issue by ghost** [TISUnion/Carpet-TIS-Addition#82]
Hello, would it be possible to allow that for survival players as well?
Greetings.

**Comment by Fallen-Breath** [comment]
That rule is designed for creative mode only. If it applies to survival it's quite cheating and against the vanilla gameplay lore. I won't choose to do that, same as all other design-for-creative rules in this mod

**Comment by ghost** [comment]
Sad, but thanks for the fast reply 😊
(I see it just as gameplay enhancement.)
