### ISSUE TITLE
Crash with tic-TACS

### ISSUE THREAD

**Issue by aria1th** [TISUnion/Carpet-TIS-Addition#9]
not sure whether its TIS addition / tic-TACS problem 
fabric, 1.16.2 ~ 1.16.4 (all), Loader ver 0.10.8
TIS version 0.11.* (all), tic-TACS ver 0.1.2

**Comment by Fallen-Breath** [comment]
iirc tic-TACS overwrites method `ServerChunkManager#tickChunks` which causes some injection failure. not sure if there are any other conflicts

**Comment by Fallen-Breath** [comment]
Should be fixed in https://github.com/TISUnion/Carpet-TIS-Addition/actions/runs/497585109. Thanksfully it's fine to move the injection point I used to the head of the method and that should be the only incompatibility
