### ISSUE TITLE
Server is crashing

### ISSUE THREAD

**Issue by sternschnaube** [TISUnion/Carpet-TIS-Addition#90]
https://pastebin.com/raw/kr7GWikH

Hello, I was updating to the newest Fabric API and Carpet Version 1.19.3 - I think that's the problem.

**Comment by Fallen-Breath** [comment]
Probrably conflicts with the latest fabric-carpet 1.4.96 for mc1.19.3. You need to downgrade fabric-carpet or wait for the compatibility fix

**Comment by Fallen-Breath** [comment]
Fixed in v1.45

**Comment by venaminecraft** [comment]
Thanks 😇
