### ISSUE TITLE
[1.19.2 Crash] Watchdog

### ISSUE THREAD

**Issue by itsdinkd** [TISUnion/Carpet-TIS-Addition#91]
Found this on my dedicated server for my modpack AQM2, wanted to report just in case. I do not know how to reproduce unfortunately. 

https://gist.github.com/itsdinkd/1821d2038a403dd541af642f1b6914a1

		carpet: Carpet Mod 1.4.84
		carpet-tis-addition: Carpet TIS Addition 1.44.0
fabric 1.19.2
0.14.13

**Comment by Fallen-Breath** [comment]
Doubt if this is related to carpet tis addition since watchdog crash usually just means your server is lagging a lot

**Comment by itsdinkd** [comment]
While true, watchdog does mean the server is just _'lagging'_ a lot, **however** this does not rule out mods stalling the server causing a watchdog crash as the point of watch dog is to prevent a infinite stall.

**Comment by Fallen-Breath** [comment]
> While true, watchdog does mean the server is just _'lagging'_ a lot, **however** this does not rule out mods stalling the server causing a watchdog crash as the point of watch dog is to prevent a infinite stall.

Then show me how is that related to this mod, e.g. give steps to reproduce the crash with this mod, then remove this mod and see if the game does stop crashing
