### ISSUE TITLE
[1.19.2] - Lithium update crash

### ISSUE THREAD

**Issue by DemonSlayer112** [TISUnion/Carpet-TIS-Addition#93]
## Description
Im not very sure to whats causing it but the mod Lithium updated for 1.19.2 and started crashing when its with this mod.
Fabric ModLoader version 0.14.14 and 0.14.17 both have same issue.

## To Reproduce
Install [lithium-fabric-mc1.19.2-0.11.1.jar](https://www.curseforge.com/minecraft/mc-mods/lithium/files/4439700)
Also this mod itself: [carpet-tis-addition-mc1.19.2-v1.44.0.jar](https://www.curseforge.com/minecraft/mc-mods/carpet-tis-addition/files/4250820)

Launch game in 1.19.2

## Environment

Describe the environment to reproduce this bug:

- Minecraft version: '1.19.2'
- Fabric Carpet version: '1.19.2-1.4.84+v221018'
- Carpet TIS Addition version: '1.19.2-v1.44.0'
- Other related mod versions: 'Lithium 1.19.2-0.11.1'
- ...

## Log
[latest.log](https://github.com/TISUnion/Carpet-TIS-Addition/files/10998220/latest.log)

If it's a crash, send the corresponding Minecraft log in the `logs` folder, or crash report in the `crash-reports`, as attachment here.

**Comment by DemonSlayer112** [comment]
Using [lithium-fabric-mc1.19.2-0.11.0.jar](https://www.curseforge.com/minecraft/mc-mods/lithium/files/4427061) seems to work just fine, so i guess something in 0.11.1 made a change carpet tis addition did not like.

**Comment by Fallen-Breath** [comment]
Same as #92

mc1.19.2 is not in the support list of Carpet TIS Addition though. You need to upgrade to mc1.19.3/4 or use old version of mod

**Comment by Fallen-Breath** [comment]
The fix is simple so I make a quick port in branch `misc/1.19.2-lithium0.11.1-compact`

You can take the builds in https://github.com/TISUnion/Carpet-TIS-Addition/actions/runs/4445216571, which is [build-artifacts-36b50e1bf760026d061bb912a6d4aaeef5964f4c.zip](https://github.com/TISUnion/Carpet-TIS-Addition/files/10999171/build-artifacts-36b50e1bf760026d061bb912a6d4aaeef5964f4c.zip). Take the jar in the `1.19.x` folder

**Comment by suerion** [comment]
Why is 1.19.2 not Supportet from TIS? the most common Mods for Fabric are on state for 119.2, A lots of Mods are in work for 1.19.3 or 1.194, but not released yet.

I don't get, why the most used 1.19.x version is not supported from some devs. 

it is only a weired way,

**Comment by Fallen-Breath** [comment]
> Why is 1.19.2 not Supportet from TIS? the most common Mods for Fabric are on state for 119.2, A lots of Mods are in work for 1.19.3 or 1.194, but not released yet.
> 
> I don't get, why the most used 1.19.x version is not supported from some devs.
> 
> it is only a weired way,

Because 1.19.2 is not the latest version for 1.19.x, not even the 2nd latest. It already takes me a lot of effort to maintain this mod for mc1.14~mc1.19 at the same time, and I don't want to maintain more Minecraft versions which are not the latest sub version

Also "mostly used" is subjective, and this mod is mostly designed for technical Minecraft, so I don't care about those "most common mods"

**Comment by DemonSlayer112** [comment]
aw, was making a modpack with it xD
Guess ill need to keep lithium downgraded.
Am i even able to edit the mod if i plan to publish it on CF? (Using only your fix of course)

**Comment by suerion** [comment]
> > Why is 1.19.2 not Supportet from TIS? the most common Mods for Fabric are on state for 119.2, A lots of Mods are in work for 1.19.3 or 1.194, but not released yet.
> > I don't get, why the most used 1.19.x version is not supported from some devs.
> > it is only a weired way,
> 
> Because 1.19.2 is not the latest version for 1.19.x, not even the 2nd latest. It already takes me a lot of effort to maintain this mod for mc1.14~mc1.19 at the same time, and I don't want to maintain more Minecraft versions which are not the latest sub version
> 
> Also "mostly used" is subjective, and this mod is mostly designed for technical Minecraft, so I don't care about those "most common mods"

sorry, i'm only a little bit frustrated, your work is awesome. it works fine, it is okey, sorry to worry you

**Comment by Fallen-Breath** [comment]
> aw, was making a modpack with it xD Guess ill need to keep lithium downgraded. Am i even able to edit the mod if i plan to publish it on CF? (Using only your fix of course)

`v1.44.0-backport.1` is released
