### ISSUE TITLE
renewableDragonEgg not summoning new egg

### ISSUE THREAD

**Issue by pupabroth** [TISUnion/Carpet-TIS-Addition#96]
## Description

Is renewableDragonEgg working? I've gone through over 2 stacks of dragon's breath (using a clock to activate a dispenser every so often) and have yet to receive another one. Am I doing something wrong?

![2023-04-05_09 13 18](https://user-images.githubusercontent.com/109471528/230108405-4fced551-7295-47b0-a4d8-47a460e1ad28.png)

## To Reproduce

1. Enable renewableDragonEgg and dispensersFireDragonBreath
2. Place a dispenser and a dragon egg in front of it.
3. Activate the dispenser.

What you expect to see: a new dragon egg to be summoned (or at least sometimes).

What actually happens: nothing.

## Environment

Describe the environment to reproduce this bug:

- Minecraft version: 1.19.2
- Fabric Carpet version: 1.4.83
- Carpet TIS Addition version: 1.39.0

**Comment by Fallen-Breath** [comment]
Minecraft caches the "randomtick-able" attribute of a block state since mc1.19+, which causes the issue

**Comment by Fallen-Breath** [comment]
Fixed in `v1.46.2`, or `v1.44.0-bp.2` for mc1.19.2
