### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Obydux** [TISUnion/Carpet-TIS-Addition#98]
## Environment

Describe the environment to reproduce this bug:

- Minecraft version: '1.19.4'
- Fabric Carpet version: '1.4.101'
- Carpet TIS Addition version: '1.46.2'
- Other related mod versions: '...'
- ...

## Log

If it's a crash, send the corresponding Minecraft log in the `logs` folder, or crash report in the `crash-reports`, as attachment here.
[latest.log](https://github.com/TISUnion/Carpet-TIS-Addition/files/11223536/latest.log)

**Comment by Fallen-Breath** [comment]
It seems to be a environment issue. Something makes this mod work wrongly. Try remove inrelated mods and make a minimum-reproduceable environment

**Comment by Fallen-Breath** [comment]
closed as being stale
