### ISSUE TITLE
Double Barrel & Hopper item teleportation

### ISSUE THREAD

**Issue by tesseract-two** [TISUnion/Carpet-TIS-Addition#99]
With Carpet's `movableTileEntities` & this mod's `largeBarrels` rules enabled, hoppers will continue to transfer items to large barrels after they are moved away.
![2023-04-13_14 26 56](https://user-images.githubusercontent.com/118913639/231851049-a7de284c-5251-4f3d-8ef9-b6167a6dc12b.png)
![2023-04-13_14 27 18](https://user-images.githubusercontent.com/118913639/231851063-4914139a-f6d2-436c-a22f-060192bbd3cb.png)
![2023-04-13_14 27 28](https://user-images.githubusercontent.com/118913639/231851052-bd1a6a58-0cd3-4b20-b74b-10e236eae21e.png)

Reproduced in Minecraft 1.19.4 & 1.19.2

Minnecraft 1.19.4
> Carpet Mod - 1.4.101+v230219
Carpet TIS Addition - 1.46.1
Fabric API - 0.78.0+1.19.4
Lithium - 0.11.1
Mod Menu - 6.1.0-rc.4
No Telemetry - 1.7.0
Sodium - 0.4.10+build.24
Starlight - 1.1.1+fabric.ae22326

Minecraft 1.19.2
> Carpet Mod - 1.4.84
Carpet TIS Addition - 1.44.0-bp.2
Fabric API - 0.76.0+1.19.2
Lithium - 0.11.1
Mod Menu - 4.2.0-beta.2
No Telemetry - 1.7.0
Sodium - 0.4.4+build.18
Starlight - 1.1.1+fabric.ae22326

**Comment by Fallen-Breath** [comment]
try remove lithium. its hopper optimization might be the cause

**Comment by tesseract-two** [comment]
It works properly without Lithium.

**Comment by Fallen-Breath** [comment]
Try test with other inventory blocks, e.g. double chest, single barrel / chest, droppers. If the same issue occours, then it's caused by the incompatibility between carpet's `movableBlockEntities` rule and lithium, and I'll suggest to report this issue to lithium or carpet

**Comment by tesseract-two** [comment]
Oops, you were right, this happens with chests, etc, without TIS Addition installed. I'll move this to the Carpet Mod repository.

**Comment by tesseract-two** [comment]
https://github.com/gnembon/fabric-carpet/issues/1704
